### ISSUE TITLE
I use Apple Push Service for export file .pem but everything normal. Is that valid?

### ISSUE THREAD

**Issue by hoavm2017hblab** [twilio/voice-quickstart-swift#101]
### With step 8
[8. Create a Push Credential with your VoIP Service Certificate]
https://github.com/twilio/voice-quickstart-swift#bullet8
### I Did:

1. I use Apple Push Service for export file .pem and paste the certificate and private key extracted from my certificate
2. But i still can make outgoing call and receive incoming call.

### My question

Is that valid? And what affects my project???

Someone help me :( Thank you so much <3

--------------
#### Voice iOS SDK
[2.0.0-beta19 via CocoaPods]

#### Xcode

[9.x]

#### iOS Version

[ > 10.3.3]

**Comment by bchen-twilio** [comment]
Hi @hoavm2017hblab 

Thanks for choosing the Twilio Programmable Voice SDK.
Let me try to understand the question:
- Are you able to export the cert and key from your VoIP Service certificate as the instructions say in the README?
- I am assuming that making outgoing call works great, but how about incoming calls? are you able to successfully register and receive incoming calls via push notifications?

By the way I noticed that you are using `beta19`. Please update the `Podfile` and point the reference to `2.0.1` for the latest SDK.

Thanks.
-bobie

**Comment by hoavm2017hblab** [comment]
Hi @bchen-twilio  Thank you so much.
- Are you able to export the cert and key from your VoIP Service certificate as the instructions say in the README?
- Answer: I was wrong to export by Apple Push Service in Keychain Access

- I am assuming that making outgoing call works great, but how about incoming calls? are you able to successfully register and receive incoming calls via push notifications?
- Answer: Yes. I can register and receive incoming calls via push notifications.

I have one Question:
- If I do not accept a notification from my device, can I receive a call?

**Comment by bchen-twilio** [comment]
Hi @hoavm2017hblab,

Thanks for getting back with the information.
By "do not accept a notification from my device", did you mean that you don't allow the notification permission when iOS is asking?

**Comment by hoavm2017hblab** [comment]
"Did you mean that you don't allow the notification permission when iOS is asking?"
Yes.

**Comment by bchen-twilio** [comment]
The application needs to first be able to respond to the notifications so that it can receive callbacks 
 from`PushKit`. In the application implementation you can add codes to check if the notification permission has been granted by the user and handle accordingly, for example pop up an alert in the app asking the user to enable notifications in system settings in case the permission was denied.

**Comment by hoavm2017hblab** [comment]
@bchen-twilio Thank you so much for answer.

**Comment by bchen-twilio** [comment]
Cool! I am closing this issue assuming the original question has been answered. Please don't hesitate to reach out to the team if you run into any problem using the Voice SDK.

Thanks!
