### ISSUE TITLE
Outbound call Disconnect Issue

### ISSUE THREAD

**Issue by Mahawbc** [twilio/voice-quickstart-swift#118]
**Outgoing call reject not working**

When i make outgoing call its connecting to receiver. In receiver side before pick the call they disconnect the call it disconnected but in sender side call not disconnecting. timer for the call duration still running after the call disconnected by receiver side. 

**Voice-quickstart-andriod-sdk**

Android studio 3.0.1
Android Build version  25.0.0
Android Gradle Version "com.android.tools.build:gradle:2.3.0"
target sdkversion 23

**Comment by bchen-twilio** [comment]
Hi @Mahawbc 

Is this happening to you both on Android and iOS? If this is an Android Voice SDK issue, please go to [Android Voice Quickstart](https://github.com/twilio/voice-quickstart-android) and file a new issue.

Thanks
-bobie

**Comment by promaticsIosTeam** [comment]
Hi Dear , 
 i was using twillio api with call kit in swift , but problem is that  i have implement  these delegate TCDeviceDelegate,TCConnectionDelegate and in which func connectionDidDisconnect(_ connection: TCConnection) {
        

        print(connection)

        

        AppDelegate.shared.providerDelegate.providers.reportCall(with: UUID(), endedAt: nil, reason: .failed)

        

        self.timingDelegate?.setTimingState(isCallReceivedOrAccpt: false, connectionState: "disconected")

        

        for call in AppDelegate.shared.callManager.calls{

            

            CallManager.manager.end(call: call)

            

        }



  This func is not called in reciver side when sender hang up call , but func is called on sender side   when call is hang up by receiver side , we are implement this using call kit in swift language , Please provide us desire solution for it

**Comment by bchen-twilio** [comment]
Hi @promaticsIosTeam 

The Twilio Client 1.2 SDK is not supported anymore and please follow this [quickstart guide](https://github.com/twilio/voice-quickstart-swift/#quickstart) to integrate the Programmable Voice iOS SDK (4.0) to your application.

In a alice-to-bob call scenario, the caller will receive the `callDidConnect:` delegate callback when the call is connected between the caller and Twilio Voice service. The callee only receives the `callDidConnect:` callback after calling `call.accept()` and connected to the call.

Let us know if you have any trouble using the Programmable Voice SDK.

Thanks,
-bobie
