### ISSUE TITLE
Unable to register for receiving calls

### ISSUE THREAD

**Issue by elyalvarado** [twilio/voice-quickstart-swift#120]
### Description

Suddenly since this morning, all my users are unable to register to receive calls. The error happens when calling TwilioVoice.register(withAccessToken: token, deviceToken: voipToken), and this IS the log message:

2018-03-22 12:22:14.997110 Happy Development[21206:1238100] [ERROR TwilioVoice] Inside register:deviceToken:completion:, failed to register for Twilio push notifications. Error:Http status: 503. Unexpected registration response.

### Steps to Reproduce

1. Call TwilioVoice.register

#### Expected Behavior

Succesful registration

#### Actual Behavior

Failure in registration

#### Reproduces How Often

Every time with all users since today 2018-03-22 around noon EST

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

TwilioVoice (2.0.1) via CocoaPods

#### Xcode

Version 9.2 (9C40b), however We've different app versions compiled with previous versions of Xcode that are also failing

#### iOS Version

All >= 8.0

#### iOS Device

All

**Comment by idelgado** [comment]
Thanks for reporting this and we apologize for the downtime. We have resolved this [issue](https://status.twilio.com/incidents/7w6mcpdh9bk7). Registration is operational again.

**Comment by elyalvarado** [comment]
Thanks
