### ISSUE TITLE
Trouble finding twilio status/event for network loss in active call.

### ISSUE THREAD

**Issue by TusharKonstant** [twilio/voice-quickstart-swift#126]
### Description
i am having trouble in finding any status or event that is invoked when remote participant network drops in an active on-going call. 

### Steps to Reproduce
1) Device A calls Device B
2) Device B accepts the call.
3) Now Call is Active and hear voice at both ends.
4) Now Device A turns his Network connection off in active call.
5) Device B now unable to hear any voice in the call. and call status is still showing connected.

i want to inform device B user that Device A user has lost internet connection or disconnected .

**Comment by bchen-twilio** [comment]
Hi @TusharKonstant 

On device A is there any other network interfaces available? ideally the SDK should fall over to another interface which has network connectivity and tries to re-connect the active call. After a short blip, the audio should be back once the re-connect is done.

If for some reason the connectivity is lost but no reachability event happens, the SDK will keep the call going though the other party won't hear audio. This is a known case and we have a ticket to come up with a better solution.

Thanks.
-bobie

**Comment by TusharKonstant** [comment]
Hi @bchen-twilio , thanks for your reply
 I want to ask that i have enable logs level. Following logs i got when network connection is lost:-

2018-04-04 12:29:39.854906+0530 Oyraa[1556:397427] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 24;
    "audio_level_out" = 0;
    "call_sid" = CA5324755452e181ce28b496921ea5820d;
    jitter = "7.25";
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 89;
    timestamp = "2018-04-04T12:29:39.854+05:30";
    "timestamp_ms" = 1522825179854;
    "total_bytes_received" = 198720;
    "total_bytes_sent" = 320000;
    "total_packets_lost" = 0;
    "total_packets_received" = 1242;
    "total_packets_sent" = 2000;
}
2018-04-04 12:29:40.854187+0530 Oyraa[1556:397673] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 30;
    "audio_level_out" = 0;
    "call_sid" = CA5324755452e181ce28b496921ea5820d;
    jitter = "7.25";
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 89;
    timestamp = "2018-04-04T12:29:40.854+05:30";
    "timestamp_ms" = 1522825180853;
    "total_bytes_received" = 198720;
    "total_bytes_sent" = 328000;
    "total_packets_lost" = 0;
    "total_packets_received" = 1242;
    "total_packets_sent" = 2050;
}
2018-04-04 12:29:41.855120+0530 Oyraa[1556:397673] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 22;
    "audio_level_out" = 0;
    "call_sid" = CA5324755452e181ce28b496921ea5820d;
    jitter = "7.25";
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 89;
    timestamp = "2018-04-04T12:29:41.854+05:30";
    "timestamp_ms" = 1522825181854;
    "total_bytes_received" = 198720;
    "total_bytes_sent" = 336000;
    "total_packets_lost" = 0;
    "total_packets_received" = 1242;
    "total_packets_sent" = 2100;
}
here  "packets_received" = 0;  and  mos = 1; which indicate that their is no network connection ,
As these are your internal sdk logs , Is their any way we can access these information in your sdk or can we use this api :- "/Calls/{callSid}/Metrics" for showing network status in Application.

**Comment by bchen-twilio** [comment]
Hi @TusharKonstant 

Thanks for providing the log. Indeed we did exactly approach to determine whether a call is experiencing connectivity issue by checking the quality stats of the calls, and eventually surface the issue to the application. We are doing a series of media stack improvements and hopefully we can leverage the new quality data to provide better experiences to the applications.

The Insights API does let you access the quality stats, but it is not real-time due to backend database implementation so I am afraid the applications can't use this approach to measure call quality in real-time.

Thanks
-bobie

**Comment by ramohanreddy** [comment]
Hi @TusharKonstant , Hi @bchen-twilio 
How to you check network connection is lost when Outgoing and incoming call time.
Can you please help on this

**Comment by bchen-twilio** [comment]
Hi @ramohanreddy 

Using the reachability module you should be able to detect connectivity change events in your app.
