### ISSUE TITLE
Readme is out of date

### ISSUE THREAD

**Issue by brandonroth** [twilio/voice-quickstart-swift#129]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Voice SDK Guides](twilio.com/docs/api/voice-sdk)
>  * [GitHub Issues](https://github.com/twilio/voice-quickstart-swift/issues)
>  * [Changelog](https://www.twilio.com/docs/api/voice-sdk/ios/changelog)

### Description

Step 2 of the readme says to go to https://www.twilio.com/console/voice/runtime/api-keys and create an api key.  Afterwards step three says 

"Follow the instructions in the server's README to get the application server up and running locally and accessible via the public Internet. For now just replace the Twilio Account SID that you can obtain from the console, and the API_KEY and API_SECRET you obtained in the previous step."

However when following the instructions to create an api key I see `sid` and `secret`.  I do not get an api key. Please see the following screenshot.

![screen shot 2018-05-15 at 3 27 47 pm](https://user-images.githubusercontent.com/2396290/40084527-a81a6b5e-5854-11e8-948f-8a65e293ccdc.png)

### Steps to Reproduce

1. Follow steps 2-3 in the readme and attempt to find the api key.

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

The instructions should match the behavior of the website.

#### Actual Behavior

They don't match.

#### Reproduces How Often

100%

#### Logs

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

[e.g. 2.0.0-beta13 via CocoaPods]

#### Xcode

[e.g. 8.3.3]

#### iOS Version

[e.g. 10.3.3]

#### iOS Device

[e.g. iPhone 6s Plus]

**Comment by bchen-twilio** [comment]
Hi @brandonroth 

Thanks for reporting this and we are sorry about the name confusion. The `SK{32}` SID is actually the API key that is needed in your access token, as well as the secret.

Please let us know if the access token works if you put the API Key SID and secret in the server variable.

Thanks.
-bobie
