### ISSUE TITLE
Query: Adding CallKit Support in the existing app

### ISSUE THREAD

**Issue by ojhakapil** [twilio/voice-quickstart-swift#130]
Hi @bchen-twilio 

We are currently using Twilio VoIP calling in our app. When I added Twilio in the app I followed the `TwilioVoiceQuickStart` project. So in the current application when an incoming call comes when the app is in background mode or when the device is locked, a notification is delivered to the user, alerting about the incoming call. Now the client wants that some of the users are missing calls because they have to unlock the screen.

As far as I know, the only solution is to use CallKit. But **I don't want to use the native call UI for all incoming calls**. Only the calls that are made when the app is in background or device is locked should show the native phone UI, in all other cased the custom incoming call screen from the app should be shown.

I would like to know from you that is this possible? If yes, what changes do I need to make in my existing workflow. 

Please let me know.

Thanks

**Comment by bchen-twilio** [comment]
Hey @ojhakapil 

Sorry for responding back to this issue with some delay.
If I am understanding correctly, you can adjust your application logic by checking the `applicationState` value of `UIApplication`.

-bobie

**Comment by amtdevops** [comment]
@ojhakapil 
Have you found any solution?

What we want is to use our Custom UI for receiving calls and should have a control on that incoming screen custom UI fully with twilio services. Is this possible to do?

**Comment by bchen-twilio** [comment]
Hi @amtdevops 

The Voice iOS SDK uses Apple's VoIP notification to notify mobile clients of incoming call invites and with PushKit + CallKit policy of the latest iOS (13), reporting to CallKit is mandatory. Native call UI will pop up once the incoming call is reported to CallKit, but app users can tap on the app icon in the system call UI to go back to the application if the incoming is received when the device is not locked.
