### ISSUE TITLE
Poor Voice quality

### ISSUE THREAD

**Issue by ojhakapil** [twilio/voice-quickstart-swift#133]
Hi Twilio Support,

Some of our customers are reporting issues with poor voice quality on incoming and outgoing calls in the iPhone app. Is there any way to resolve this? The iPhone build uses Twilio Voice 2.0.0- beta14.

**Comment by ojhakapil** [comment]
Hi @bchen-twilio 

I will provide you Call SIDs of all the users who are facing the issue.

Thanks

**Comment by bchen-twilio** [comment]
@ojhakapil Much appreciated! 👍

**Comment by bchen-twilio** [comment]
Closing this issue. Please feel free to open a new issue if you run into poor audio quality issue in the future.
