### ISSUE TITLE
Push notification when the app is closed

### ISSUE THREAD

**Issue by demetrio812** [twilio/voice-quickstart-swift#136]
Hello,
I've ran the app and it works very well, the only thing that doesn't work is the incoming call notification when the app is stopped, as soon as I open the app I see the accept/reject dialog.

Is it something I did wrong or I'm missing or there is no support for it?

Thanks,
Dem

**Comment by bchen-twilio** [comment]
Hi @demetrio812 

I am assuming by "when the app is stopped" you meant the app was terminated, right? One thing you can try is to see if the app is configured following the instructions in the [background capabilities section](https://github.com/twilio/voice-quickstart-swift#9-configure-xcode-project-settings-for-push-notifications).

Have you tried using the quickstart and see if call notification works in your environment when the app is terminated?

Thanks
-bobie

**Comment by demetrio812** [comment]
Hello @bchen-twilio , thanks for the response, I did more tests and what I notice if the following behaviours:

1) when the app is opened I receive calls properly
2) if the app is closed (not only terminated, also in background) and I start a call from the other phone, I don't get any push notification telling me there is an incoming call, if I manually open the app the accept/reject dialog will immediately trigger
3) if the app is closed (not only terminated, also in background) and I start a call from the other phone, I don't get any push notification telling me there is an incoming call, if I wait until the call request is automatically terminated, as soon as it's terminated I get the notification "incoming call" on the phone when the app is closed.

So it looks like the notification "incoming call" is only sent when the call requests is terminated, going to check it and see if I understand why, any suggestions?

Thanks,
Dem

I've tried the quickstart, and added the background capabilities (the voip is not showing in the ui, added it manually in the plist file), push notification and created the voip service certificate and uploaded online...

**Comment by bchen-twilio** [comment]
Hi @demetrio812 

Thanks for the additional debugging info.
Since the SDK doesn't track the inactive-states (it does listen to the `UIApplicationDidBecomeActiveNotification` notification, but only to check if the network connectivity is working), it seems that the app somehow is not able to show notifications when the it is backgrounded or terminated.

I've tried the Swift quickstart and I did see the `callInviteReceived:` delegate method being called when the app is in the background.

Is the app showing incoming call alerts using `UILocalNotification`?

**Comment by demetrio812** [comment]
Hello @bchen-twilio,
yes, it looks like sometimes is working and (many) other times it isn't, I will try to find out if there is a pattern and update the ticket.

I also have another question but I will open another ticket for it, thanks

**Comment by bchen-twilio** [comment]
@demetrio812 That would be great!

It would also be great if you can help us check if call notifications are always sent and received by the app, **when it is in the foreground**. It doesn't seem like a delivery issue on Twilio's end, but just want to make sure since we need to investigate delivery issue in a different way.

**Comment by devlove1C** [comment]
Hello Team,
I've ran the app and it works very well, the only thing that doesn't work is the incoming call notification when the app is in background or terminated.
When the app is in background **callInviteReceived** method called, but how can i launch the app in this condition.

Thanks,
Dev

**Comment by Maubic** [comment]
Hello @bchen-twilio ,

Same here. I am trying both Quickstart and QuickstartCallkit with the same result.

As far as I can see, while debugging the app in Xcode the notification is received and NSLog is printed. Sometimes it takes more than 10 seconds until callkit view is opened, but it usually works.

However, when the iphone is detached from Xcode and the app run by itself, callkit view only appears if the app is in foreground, as reported by @dmetrio812

I will keep trying, but I am running out of ideas...

**Comment by anonrig** [comment]
I'm having the same issue. When app is terminated or in background I don't receive notifications. It seems that UILocalNotification doesn't fire when the app is in background or terminated.

An example issue on StackOverflow can be found from: https://stackoverflow.com/questions/20037737/uilocalnotification-scheduled-in-background-doesnt-fire.

So, we shouldn't rely on UILocalNotifications for handling push notifications. On the other hand, I don't have any errors on console or in Twilio Dashboard related to APN or push notifications. 

Any suggestions @bchen-twilio ?

**Comment by anonrig** [comment]
Additionally, in appdelegate.m the example code doesn't register for remote notifications: https://github.com/twilio/voice-quickstart-swift/blob/master/SwiftVoiceQuickstart/AppDelegate.swift#L65

we need to add `application.registerForRemoteNotifications()`

**Comment by bchen-twilio** [comment]
Hi all,

We have updated the sample app recently to address the background-suspended issue in iOS 12. Please refer to [this PR](https://github.com/twilio/voice-quickstart-swift/pull/201) and apply necessary updates to your application to resolve the issue.

Thanks
-bobie

**Comment by anonrig** [comment]
Does this work with the Pushkit without Callkit?

**Comment by bchen-twilio** [comment]
Hi @anonrig 

Yes, the updates in the PR have fixes for both the CallKit and regular (PushKit w/out CallKit) quickstarts.

**Comment by bchen-twilio** [comment]
Hi all,
I am closing this ticket and assuming the updates should have addressed the original issue. Please feel free to create a new issue or reach out to the team if you run into any issue.

Thanks!
-bobie
