### ISSUE TITLE
How to call from app to a number which is not A verified phone number 

### ISSUE THREAD

**Issue by phukhanhlee** [twilio/voice-quickstart-swift#140]
Firstly, I want to thank the team who make awesome demo app.
But in step 12. Make client to PSTN call

"To make client to number calls, first get a valid Twilio number to your account via https://www.twilio.com/console/phone-numbers/verified. Update your server code and replace CALLER_NUMBER with the verified number"
I create one phone number for CALLER_NUMBER.

But I just only to call to verified phone number (I added another phone number to "Verified Caller IDs"). Can I call to any phone number ? or Do we support an API to create verified phone number automatically ? So I can call phone App to any number.

**Comment by bchen-twilio** [comment]
Hi @phukhanhlee 

Thanks for choosing the Voice iOS SDK.
To call to any phone number, you need to make sure you have enabled the [geo-permission](https://www.twilio.com/console/voice/calls/geo-permissions/low-risk) for that specific region/country.
Once the permission of the region is enabled, follow the quickstart you should be able to place a call from the SDK/app to the number.

cheers,
-bobie

**Comment by phukhanhlee** [comment]
Hi @bchen-twilio Thanks for your quick response. But i still can't call out to another number. I already enable "geo-permission" for my country to test. I just call out to "[verified phone number](https://www.twilio.com/console/phone-numbers/verified)". I can't call to another phone number in my contacts (which aren't verified).

**Comment by phukhanhlee** [comment]
I see. May be I'm in trail mode !

**Comment by bchen-twilio** [comment]
Closing this issue for now. Please feel free to create new issue in the future.
