### ISSUE TITLE
Incoming calls failing randomly

### ISSUE THREAD

**Issue by ojhakapil** [twilio/voice-quickstart-swift#141]
Hello Twilio Support,

This is to inform you that some of our customers are not receiving incoming calls 100% of the time. They are saying that this is only happening in iOS but Android seems to be working correctly.

When we tried to reproduce the issue at our end we found that for some calls when `callInviteReceived` is called the value of .`state` is `canceled` instead of `received`, hence we don't get an incoming call. This is happening when the app is in background mode or device is locked. We have been able to find this by adding alerts when an incoming call comes.

We were unable to reproduce it when we tried to debug it, so won't be able to provide any logs.

We are using CallKit to report incoming call and have followed the CallKitQuickStart example.

The version of Twilio Voice we are using is 2.0.4

Thanks

**Comment by bchen-twilio** [comment]
Hi @ojhakapil 

Thanks for reporting the issue. Can you help us check the [Programmable Voice Dashboard](https://www.twilio.com/console/voice/dashboard) and see if there is error/warning being logged related to call notification delivery failure? We can ask the Twilio Notify team to debug if there are delivery failures, otherwise we can debug on the application/SDK side to see why notifications are not shown when not in the foreground.

Please provide Call SIDs that you think are experiencing delivery issues.
Thanks.

-bobie

**Comment by ojhakapil** [comment]
Hi @bchen-twilio 

I checked the Programmable Voice Dashboard and saw the error: **11200 HTTP Retrieval Failure** for the call that reproduced the issue.

Here are call SIDs for a couple of calls for which I reproduced the issue on our Demo account on Twilio.

1. Call SID: CA642693770dd444e2002c238330418ada
   Child Call SID: CA812eb33a87862cbea122c36a4b6489fa

2. Call SID: CA89c034907c7a1ed25dbd6cd3ffcf4566
    Chile Call SID: CA38fd7f3ccc61b8d8ec57870823a34605

please let me know if you need anything else from my end.

Thanks

**Comment by ojhakapil** [comment]
Hi @bchen-twilio 

have you got chance to view my comments. This is a critical issue faced by lot of our live users which is impacting their business.

Thanks

**Comment by bchen-twilio** [comment]
Hi @ojhakapil 

The Twilio [11200 error code](https://www.twilio.com/docs/api/errors/11200) usually indicates that Twilio service encountered a problem fetching contents from the URL specified by the TwiML.

I've checked the Call SIDs you provided and they both showed `no-answer`. No delivery failure of the child Call SIDs. Please check the application implementation and ensure that the `PkPushRegistry` logics can be reached when the app is not in the foreground and the calls are correctly reported to the CallKit provider.

Thanks
-bobie

**Comment by ojhakapil** [comment]
Hi @bchen-twilio 

Thanks for your response.

I don't thing it has anything to do with 11200 error code. I had a discussion with our back end developer and he told me that this error came because I was trying to access a url on his local machine at at time when the server was down.

I have also checked the application implementation and can verify that `didReceiveIncomingPushWithPayLoad` is getting called.

Thanks

**Comment by ojhakapil** [comment]
Hi @bchen-twilio 

One more thing I would like to share with you is that in my `handleCallInviteReceived` method, I first call an API and then once I have the response of that API, I call `reportIncomingCall`.

Is there any possibility that this is why incoming calls are not reported  when the app is put in background?

Thanks

**Comment by bchen-twilio** [comment]
Hi @ojhakapil 

Can you describe more about the API you called when the call invite is received?
- is it a RESTful request?
- is it returning results asynchronously or synchronously?
- random thoughts, but is the API result coming back on the same dispatch queue where the `callInviteReceived:` method is invoked?

Thanks
-bobie

**Comment by bchen-twilio** [comment]
Closing since the original issue has been answered. For the issue where call is not reported when the app is backgrounded, please check out the updates in [this pull request](https://github.com/twilio/voice-quickstart-swift/pull/195).
