### ISSUE TITLE
Keep getting 52004 (Credential SID not specified) and 52131 (Invalid APNs credentials)

### ISSUE THREAD

**Issue by StratRob** [twilio/voice-quickstart-swift#145]
### Description

Hi, I am new to Web RTC development and trying to implement TwilioVoice into my app. 
I am following the tutorial and everything works fine from steps 1 to 6. I have correctly setup a local Java server, a tunnel with ngrok, added TwilioVoice into my iOS app with Cocoapods, created a TwiML app and configured the server. When I simply start a call, I get the _congratulations_ message from the server.

However, almost every time I try to call `/placeCall`, I get two errors in the dashbord's log, and none of the delegate `PKPushRegistry` and `TWONotification` methods get called.

<img width="1020" alt="capture d ecran 2018-07-09 a 17 49 51" src="https://user-images.githubusercontent.com/25252204/42461356-9ade037a-83a0-11e8-9abe-b71557d0b2ca.png">

What I don't understand is why it worked a few times first, for like 5 minutes, and now it's not working anymore, no matter what I try. 

As you can see, the app seems to correctly register to push notifications : 

![capture d ecran 2018-07-09 a 17 54 03](https://user-images.githubusercontent.com/25252204/42461670-58a29362-83a1-11e8-95d8-8bec57442216.png)

In order to create the push credentials, I have created a VoIP services certificate for my app from the Apple Developer Center, then added it to the keychain access and exported it to a .p12 file, followed the 8th step to create `cert.pem` and `key.pem`, added these values to a APN credentials (pasting all the content including BEGIN/END parts) and ticking the sandbox checkbox, added the credential SID to the server's `.env` file, added `voip` and `audio` to the background modes of my app... and I keep getting these issues.

PS : nothing has been deployed to production, I'm getting these errors in development mode using sandbox mobile push credentials.

#### Expected Behavior

Catching the notification of an incoming call.

#### Actual Behavior

Nothing happens client-side although the app correctly registers to Twilio push notifications.

#### Reproduces How Often

It quickly worked for a few times, then suddenly stopped working.

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

TwilioVoice 2.0.0 with CocoaPods.

#### Xcode

Version 9.4

#### iOS Version

Version 11.4

#### iOS Device

iPhone SE

**Comment by bchen-twilio** [comment]
Hi @StratRob 

Sorry that you are experiencing the problem. The error code of the notification delivery failure does seem odd to me but I am happy to help you out.
Can you provide us a call SID when you don't get a incoming call notification?
Just a hunch, but can you also use [jwt.io](https://jwt.io/) and see if all the values in the Access Token are valid?

Thanks.
-bobie

**Comment by StratRob** [comment]
Hi @bchen-twilio, and thank you for the quick reply.

I just got the reason and feel really stupid right now... I just didn't understand that I had to match the identity `alice` in order to get `/placeCall` working fine. I've set `alice` again and everything is OK now. 
However, I am not sure this is the cause of these 52004 and 52131 errors, so if you need a SID here is one : `CAa6ac6c1d0295f949faa79e7b698fc2da`

Also, I have another question : I was able to follow all the tutorial and connected two devices perfectly. However, when I call another device, the `from` value of the `callInvite` in the delegate's `callInviteReceived` is always `client:quick_start` instead of the identity of the caller. What can I do to get it instead?

Thanks a lot for your help.

**Comment by bchen-twilio** [comment]
Hi @StratRob 

The `from` value shown in the `TVOCallInvite` object is basically determined by the `callerId` of the `<Dial>` verb in the the TwiML. One thing to keep in mind is that if you want to show alphabetic values, for example `client:alice`, at the callee side, remember to prefix the value with `client:`, otherwise the value by default will be dialpad-translated into numerical values.

I've also checked the call SID but still not quite sure what exactly is wrong. Have you tried to mix credentials between accounts? credentials are not shareable even between master and subaccounts.

**Comment by StratRob** [comment]
Hi again, and thank you for your answer.

I have no clue about this credential issue, but hopefully I'm not catching it anymore... 

About the `from` value, I am sorry but I am not sure to understand what's going on. I tried to add a `from` parameter in the `TwilioVoice.call()` function, like this:

```
call = TwilioVoice.call(accessToken, 
                        params: ["from": "Test", "to": "Robin"],
                        delegate: strongSelf)
```

I have tried with and without adding `from` in `twiMLParams`, with and without uppercase and using both `Bob` and `client:Bob` as the value. No matter what I try, I always catch this result in `callInviteReceived()` :

![capture d ecran 2018-07-10 a 10 49 31](https://user-images.githubusercontent.com/25252204/42499436-18a41c84-842f-11e8-9e7a-47f1a03643cd.png)

(do you want me to create a new issue for this?)

Thanks again for your help!

**Comment by bchen-twilio** [comment]
Hi @StratRob 

I am sorry that we probably made the quickstart too simple even to demo this basic functionality. To save you from too much details, let's try this:

```
  // on mobile client A, generate an access token with identity "bob"
  call = TwilioVoice.call(accessToken, 
                        params: ["callee": "Robin"],
                        delegate: strongSelf)
```

and assuming you are using the python quickstart:
```
CALLER_ID='client:quick_start'
CALLEE_ID='alice'

def makeCall():
  caller = request.values.get('From', CALLER_ID)
  callee = request.values.get('callee', DEFAULT_CALLEE)
  response = VoiceResponse()
  response.dial(callerId=caller).client(callee)
```

There are two default arguments that will be embedded in the Voice URL request, `From` and `To`, and in your use case we will be needing the `From` value here. When making a mobile client to mobile client call, this value will be derived (by the Twilio Voice service) from your access token.

You can definitely choose any arbitrary HTTP request parameters other than the capitalized `From` & `To` as your custom request params.

cheers
-bobie

**Comment by StratRob** [comment]
Got it now! Thank you again for the explanation and your time.

**Comment by bchen-twilio** [comment]
Any time!
