### ISSUE TITLE
Question: CallKit support

### ISSUE THREAD

**Issue by dasoga** [twilio/voice-quickstart-swift#15]
Hi guys, do you have support for CallKit in this beta 5?

Thank you

**Comment by bchen-twilio** [comment]
Hi @dasoga 

Bobie here from the iOS SDK team.
Yes, the iOS SDK doesn't support CallKit in beta, and we would recommend that you use our latest and greatest beta6. Please check out the CallKit sample in this repo.
Please also let us know if you have any trouble trying the steps in the README.

Looking forward to seeing your awesome Voice application!

**Comment by dasoga** [comment]
Hey man, 
I didn't realize that you've already updated the repository. Sorry for that.
I'm doing something with Salesforce and Twilio.
Really thank you for your answer

**Comment by bchen-twilio** [comment]
Hehe no worries.
Please let me know if you have any feedback or need any help.
I am going to close this ticket.
