### ISSUE TITLE
Not able to switch voice audio output to receiver

### ISSUE THREAD

**Issue by rohit-skycap** [twilio/voice-quickstart-swift#150]
As per reference from sample project this piece of code is supposed to toggle voice call audio output b/w Speakers and Receiver. But this isn't working. Only audio output for call is speakers. Kindly help. 

func toggleAudioRoute(toSpeaker: Bool) {
        // The mode set by the Voice SDK is "VoiceChat" so the default audio route is the built-in receiver. Use port override to switch the route.
        do {
            if (toSpeaker) {
                try AVAudioSession.sharedInstance().overrideOutputAudioPort(.speaker)
            } else {
                try AVAudioSession.sharedInstance().overrideOutputAudioPort(.none)
            }
        } catch {
            NSLog(error.localizedDescription)
        }
    }

**Comment by bchen-twilio** [comment]
Hi @rohit-skycap 

When `toSpeaker` is `false`, you should hear audio output from the small speaker on the top of the screen when the call is connected. Did audio always come out from the big (and louder) speaker regardless the state of the flag?
What is the device model and iOS version in your environment?

thanks
-bobie

**Comment by rohit-skycap** [comment]
Hi Bobie

Yes i have tried flags mentioned. Audio output is always from loud speaker, regardless of flag state.
Tested on iOS devices:

iPod Touch
Model : MKHT2ZP/A
OS : iOS 11.4(15F79)

iPhone 6s
Model: MKQM2HN/A
OS iOS 11.4.1(15G77)

iPad Air
Model: MD788HN/B
OS: iOS 11.2.5(15D60)

Regards
-rohit

**Comment by bchen-twilio** [comment]
Thanks Rohit.
Did you see any error message in the debugging console when you experienced this problem?

**Comment by rohit-skycap** [comment]
Hi Bobie

Any update on this?

Regards
-rohit

**Comment by bchen-twilio** [comment]
Hi Rohit,

I tried running the Swift quickstart, both regular and CallKit, and was able to switch between receiver and the speaker.

-bobie

**Comment by rohit-skycap** [comment]
Finally managed to solve this. I was using TwilioVideo and TwilioAudio configurations at same place. Which has conflicting audio sessions.

Thanks for all the help!

**Comment by ramohanreddy** [comment]
> Finally managed to solve this. I was using TwilioVideo and TwilioAudio configurations at same place. Which has conflicting audio sessions.
> 
> Thanks for all the help!

hi @rohit-skycap 

can u help me how you did getting audio on call
