### ISSUE TITLE
Problems with custom TVOCallDelegate

### ISSUE THREAD

**Issue by ream88** [twilio/voice-quickstart-swift#151]
### Problems with custom TVOCallDelegate

I have problems using my custom TVOCallDelegate when creating a call. If I follow this example here, where my view controller implements TVOCallDelegate everything is fine and working, however when I move logic into my own class implementing TVOCallDelegate, none of the callback functions are called whatsoever. 
 
#### Code

```swift
class LogToConsole: NSObject, TVOCallDelegate {
    func callDidConnect(_: TVOCall) {
        print("callDidConnect(_ call: TVOCall)")
    }

    func call(_: TVOCall, didFailToConnectWithError _: Error) {
        print("call(_ call: TVOCall, didFailToConnectWithError error: Error)")
    }

    func call(_: TVOCall, didDisconnectWithError _: Error?) {
        print("call(_ call: TVOCall, didDisconnectWithError error: Error?)")
    }
}

// in my controller
TwilioVoice.call(token, params: [:], uuid: action.callUUID, delegate: LogToConsole())
```

#### Expected Behavior

Should call the delegate and print to the console

#### Actual Behavior

Nothing

Am I doing something wrong?

**Comment by bchen-twilio** [comment]
Hi Mario,

The delegate instance must be kept alive during the lifecycle of the Call. Perhaps you would want to keep an instance var of `LogToConsole` and pass this instance to the `TwilioVoice.call()` method?

-bobie

**Comment by ream88** [comment]
Ahhh @bchen-twilio makes sense! (Still a Swift novice here) Thx a lot, closing this! 😊

**Comment by bchen-twilio** [comment]
@ream88 no problem!

**Comment by SamAndersson** [comment]
We are upgrading from TwilioVoice 2.0.0-beta18 to 2.0.7.

We get the below compiler errors:

(1) Type 'TwilioVoice' has no member 'sharedInstance'

(2) Method 'call(_:didFailWithError:)' has different argument labels from those required by protocol 

Is there an updated 'QuickStart' out there that illustrates the changes between 2.0.0-beta18 and 2.0.7?

Thank you.

**Comment by bchen-twilio** [comment]
Hi @SamAndersson 

The latest quickstart (`master` branch) is based on the latest version, 2.0.7, of the Programmable Voice SDK. You can also find [the API documentation](https://media.twiliocdn.com/sdk/ios/voice/releases/2.0.7/docs/) for more reference.

Thanks,
-bobie
