### ISSUE TITLE
Outgoing calls failing randomly 

### ISSUE THREAD

**Issue by Dhivysh** [twilio/voice-quickstart-swift#154]
Hi,
I was able to implement incoming & outgoing calls successfully with SwiftVoiceCallKitQuickstart. The only issue I have is with outgoing calls. Sometimes when placing a call, it remains in connecting stage. I've set TwilioVoice.logLevel  to .verbose and no log is generated after provider(_ provider: CXProvider, didActivate audioSession: AVAudioSession).

<b>Log:</b>
providerDidBegin
2018-08-11 22:14:26.024363+0530 Calls[1854:483557] StartCallAction transaction request successful
2018-08-11 22:14:26.050220+0530 Calls[1854:483521] provider:performStartCallAction:
2018-08-11 22:14:26.970752+0530 Calls[1854:483521] provider:didActivateAudioSession:
2018-08-11 22:14:26.970907+0530 Calls[1854:483521] [VERBOSE TwilioVoice] Enable audio.

This is usually happening on first launch of the App. 

<b>Device</b>
iPhone X
<b>iOS Version</b>
11.4.1

**Comment by bchen-twilio** [comment]
Hi @Dhivysh 

Can you provide us the full SDK logs, minus any credentials or tokens, so we can investigate further? And based on your description, were you still able to make outbound calls successfully after the first failure?

-bobie

**Comment by Dhivysh** [comment]
Hi @bchen-twilio ,
Yes I was able to place calls after the first failure. I've been trying to regenerate the issue but it is no longer happening. I'll post complete logs if this happens again. 

Thanks.

**Comment by Dhivysh** [comment]
Thanks. Closing issue for now.

**Comment by bchen-twilio** [comment]
Cool. Feel free to reach out to us in the future if you run into any issues or questions.
