### ISSUE TITLE
Getting Error: EndCallAction transaction request failed: The operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 4.)

### ISSUE THREAD

**Issue by ojhakapil** [twilio/voice-quickstart-swift#155]
Hello Twilio Support,

I am using TwilioVoice 2.0.4 for VoIP calling in my application. I have taken the sample code from `TwilioVoiceCallKitQuickStart` project. But I'm facing a random issue with it.

When `callInviteReceived` is called with `state == cancelled`, and I try to end the call, the incoming call screen from CallKit does not go away and the phone continues to ring even when the call has been disconnected by the dialer.

I'm getting the below error logged on the console:

> EndCallAction transaction request failed: The operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 4.)

I searched for the possible causes of the error and found that it comes when the UUID used in CXEndCallAction does not correspond to a known call. But if that is the case, this error should be repeated all the time, but it only happens occasionally.

Please let me know what I'm doing wrong here.

```
    func callInviteReceived(_ callInvite: TVOCallInvite) {
        NSLog("callInviteReceived:")
        
        print("Call Invite UUID: ", callInvite.uuid)
        if (callInvite.state == .pending) {
            NSLog("state == received")
            handleCallInviteReceived(callInvite)
        } else if (callInvite.state == .canceled) {
            NSLog("state == cancelled")
            handleCallInviteCanceled(callInvite)
        }
    }
    
    func handleCallInviteReceived(_ callInvite: TVOCallInvite) {
        
        if (self.incomingCallInvite != nil && self.incomingCallInvite?.state == .pending) {
            NSLog("Already a pending incoming call invite.");
            NSLog("  >> Ignoring call from %@", callInvite.from);
            
            showMissedCallNotification(callInvite)
            
            return;
        } else if (self.call != nil) {
            NSLog("Already an active call.");
            NSLog("  >> Ignoring call from %@", callInvite.from);
            
            showMissedCallNotification(callInvite)
            
            return;
        }
        
        self.incomingCallInvite = callInvite
        

        print("Reporting incoming call for uuid: ",callInvite.uuid)
        self.reportIncomingCall(uuid: callInvite.uuid)
    }
    
    func handleCallInviteCanceled(_ callInvite: TVOCallInvite) {
        //Perform End Call action
        performEndCallAction(uuid: callInvite.uuid)

        if !incomingCallDetailFromServer.isEmpty {
            DatabaseManager.saveMissedCallInCoreData(number: callInvite.from, missedCallDetail: incomingCallDetailFromServer)
        }
            
        else {
            DatabaseManager.saveMissedCallInCoreData(number: callInvite.from, missedCallDetail: [:])
        }
        
        //Show missed call notification
        showMissedCallNotification(callInvite)
        
        //set call invite to nil
        self.incomingCallInvite = nil
        
        //dismiss the alert for incoming call
        self.dismissIncomingCallAlertDelegate?.dismissIncomingCallAlert()
    }

  func performEndCallAction(uuid: UUID) {
        
        let endCallAction = CXEndCallAction(call: uuid)
        let transaction = CXTransaction(action: endCallAction)
        
        print("PerformingEndCallAction for uuid: ",uuid)
        callKitCallController?.request(transaction) { error in
            if let error = error {
                NSLog("EndCallAction transaction request failed: \(error.localizedDescription).")
                return
            }
            
            NSLog("EndCallAction transaction request successful")
        }
    }
```

**Comment by bchen-twilio** [comment]
Hi @ojhakapil 

Thanks for reporting the issue.
Just to make sure we are investigating the issue with the same steps: when you said "ending the incoming call when a .canceled call-invite is received", were you ending a connected incoming call, or a pending incoming call which has not been answered or declined?

thanks
-bobie

**Comment by ojhakapil** [comment]
Hi @bchen-twilio 

Thanks for your reply.

I was ending a pending incoming call before accepting it. We haven't seen this issue so far when ending a connected incoming call.

**Comment by bchen-twilio** [comment]
Thanks @ojhakapil 

In your `handleCallInviteCanceled()` method, can you check if the metadata (`uuid`, `callSid`) match between `callInvite` and `self.incomingCallInvite`? And I could be wrong but just a hunch: can `self.incomingCallInvite = nil` actually damage the `uuid` while CallKit is doing some asynchronous operations executing `performEndCallAction(uuid: callInvite.uuid)`?

Thanks
-bobie

**Comment by ojhakapil** [comment]
Hi @bchen-twilio 

I have checked the `handleCallInviteCalnceled()` the `uuid` and `callSid` in bot `callInvite` and `self.incomingCallInvite` seems to match.

Also, I don't think `self.incomingCallInvite = nil` can damage the uuid. I can even remove `self.incomingCallInvite` since my app logic is not dependent on it anymore.

Please have a look at the log:

Call Invite detail: UUID: D462217A-2E76-40D8-B4D2-3CB8F6B124BA, Call SID: CAc60e560aa29ea25142307038ec206a0d
self.incomingCallInvite detail: UUID: Optional(D462217A-2E76-40D8-B4D2-3CB8F6B124BA), Call SID: Optional("CAc60e560aa29ea25142307038ec206a0d")
PerformingEndCallAction for uuid:  D462217A-2E76-40D8-B4D2-3CB8F6B124BA
2018-08-17 19:03:58.809857+0530 DealerApp[2436:213876] EndCallAction transaction request failed: The operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 4.).

Please let me know how to get around with this.

Thanks

**Comment by bchen-twilio** [comment]
Hi @ojhakapil 

Sorry for my delay of responding back to this ticket.
Looks like the UUID is valid but I have a feeling that the call with the UUID has already been ended or terminated with error, so when the application was trying to actively perform the end-call action the error was returned.

**Comment by bchen-twilio** [comment]
Hi @ojhakapil 

I'll try with the Swift quickstart and see if the same error can be reproduced.
Thanks again for reporting.

-bobie

**Comment by ojhakapil** [comment]
Hi @bchen-twilio 

Please let me know if you find something that can resolve this issue.
Thanks for your support.

**Comment by bchen-twilio** [comment]
@ojhakapil 

We tried the same steps but so far no luck reproducing the end-call error.

**Comment by bchen-twilio** [comment]
Hi @ojhakapil 

Sorry for my lack of response on this issue. We've actually found that this was a bug in our CallKit example in the end-call flow. It should be fixed on. Please take a look at the PR #173 and see if the fix works for you too.

Thanks.
-bobie

**Comment by kapilojha** [comment]
Hi @bchen-twilio 

Thanks for your response on this issue. I have looked at the changes made by you in the CallKitQuickStart sample. I have one question to you about this: the change made is for outgoing call action but I faced the issue for an incoming call not disconnecting. 

So, will the new change solve the issue for me?

**Comment by bchen-twilio** [comment]
Hi @kapilojha 
The update fixed the end-call flow, include both outgoing and incoming calls.

Thanks,
-bobie

**Comment by kapilojha** [comment]
Hi @bchen-twilio 

Thanks for your quick response.

So do I need to update the Twilio Voice SDK? Currently I'm using 2.0.4. 
Also, if you have looked at the code I provided while reporting the issue, do I need to make any changes in that also?

Your support is greatly appreciated....

**Comment by bchen-twilio** [comment]
Hi @kapilojha 

2.0.4 should work fine unless the [answer-on-bridge feature](https://www.twilio.com/docs/voice/twiml/dial#answeronbridge) is enabled in your TwiML. You can take a look at the flows of how calls are reported/started/ended with the CallKit integration and compare with the implementation in you application.

-bobie

**Comment by ojhakapil** [comment]
Hi @bchen-twilio 

Still getting the error. answer-on-bridge feature is not used on the TWiML application (It should be set to default value). I have followed the flow from CallKit quick start app, the only difference is that the whole incoming call logic is put in a singleton since app can receive incoming call regardless of which screen the user is currently on.

**Comment by bchen-twilio** [comment]
Hi @ojhakapil 

The fix in #171 is to ensure that the app doesn't initiate the end-call action again (the line removed in the `call:didDisconnectWithError:` callback) after the CallKit has been ended. Can you check if your app implements the same logic?

Thanks
-bobie

**Comment by ojhakapil** [comment]
Hi @bchen-twilio 

I am getting the issue when trying to disconnect the call from dialer end before the receiver has answered it. In this case `call:didDisconnectWithError:` is not called since there is no connected call.

I have also tried removing the line from `call:didDisconnectWithError:`. But I don't think that it is disconnecting the call properly because when I try to make another call to the same number, the receiver's screen show options: "Decline", "End & Accept" but the second option should be "Accept" since the previous call has been disconnected. 

Thanks

**Comment by bchen-twilio** [comment]
Hi @ojhakapil 
Thanks for providing additional details about the issue. I'll try the same steps and let you know.
-bobie

**Comment by iChirag** [comment]
hey @bchen-twilio 
I am also facing same endCall error issue on VideoCall.
Note: I am using latest version of **TwilioVideo** 

> 2.5.3

Please let me know. What I need to do to resolved this my side?

Best.

**Comment by bchen-twilio** [comment]
Hi @iChirag 

We have recently updated the Video quickstart ([pull request](https://github.com/twilio/video-quickstart-swift/pull/327)) to address the issues around end-call error. Please feel free to create an issue in the Video quickstart repository in case you are still experiencing any issues.

Thanks!
-bobie

**Comment by Curi0sity** [comment]
I having an issue with endCall on the receiver side. Updating from 2.0.0 beta to 2.5.3 resolved this issue for me.
