### ISSUE TITLE
Calls from number to number not receiving VOIP notifications

### ISSUE THREAD

**Issue by kjmacaul** [twilio/voice-quickstart-swift#157]
We've been using the voice SDK successfully making calls from client to client. However, we're now trying to switch to making calls from number to number using purchased numbers through the Twilio Dashboard and running into issues.

We can see in the call logs on the dashboard that the calls are being attempted with no errors reported but the devices aren't receiving any VOIP notifications. Do you have any insights as to what we might be doing wrong?

**Comment by bchen-twilio** [comment]
Hi @kjmacaul 

To receive incoming call VoIP notification on the mobile client side, you always have to register an unique identity. Correct me if I am wrong, in this case, if you are making a number-to-number call and still want to get VoIP notification on a mobile client, you will need to tweak the TwiML application a little bit. Here is the python-ish pseudo code for TwiML generation:
```
# The endpoint used in the TwiML Application (SID)
def callVoiceClient:
    from_number = request.values.get('param_from')
    to_number = request.values.get('param_to')

    # Some application logic to map "to_number" to a client identity
    to_client = numberToClient(to_number)

    response = VoiceResponse()
    # `callerId` should be a valid Twilio number or in the format "client:XXXX"
    response.dial(callerId=callerId).client(to_client)

    return response

def numberToClient(number):
    # Some DB lookup
    return identity
```

Let me know if this answers your question.

cheers
-bobie

**Comment by kjmacaul** [comment]
Thanks for the quick response Bobie,

Most of that makes sense but we were under the impression that we needed to change

`response.dial(callerId=callerId).client(to_client)`
to 
`response.dial(callerId=callerId).number(to_number)`
in order to use the cellular network of the phone number.

If the value of to_client is something like `client:+1775XXXXXXX` would the cellular network of the phone number actually be used or would it still be a VOIP call?

**Comment by bchen-twilio** [comment]
The `dial().client()` actually contracts the argument to be a client identity, and the `dial().number()` takes a real number. The mobile client either gets a VoIP notification triggered by the `.client()` TwiML, or a real PSTN call if the TwiML says `.number(THE_NUMBER_ON_THE_PHONE)`.

The value in `.client()` doesn't have to be prefixed with `client:`, just the identity is good.
I haven't tried but with the response of `response.dial(callerId=callerId).client('client:+17751234567')`, Twilio Voice service will either try to reach out to `client:+17751234567` or throw an error.

I don't want to make you more confused, but to recap:
- `response.dial(callerId='17751234567').client('alice')`
  - mobile client registered with `alice` gets VoIP notification, from `17751234567`
- `response.dial(callerId='client:bob').client('alice')`
  - mobile client registered with `alice` gets VoIP notification, from `client:bob`
- `response.dial(callerId='17751234567').number('17751234568')`
  - the device with number `17751234568` gets a PSTN incoming call

Let me know if this makes sense to you ;)

**Comment by kjmacaul** [comment]
We made the change to use the format `response.dial(callerId='+17751234567').client('+15555555555')` and we receive the VOIP notifications. The outgoing call log also correctly appears for the phone number. However, the call log doesn't appear as an incoming call for the phone number of callee since since it shows as `client:+15555555555` in the logs. Is this to be expected or is the callee's phone number not being used except as a client identifier?

The call SID is `CA9b2271c7a560484303bd7df7ac655bd9` if you are able to view that information.

**Comment by kjmacaul** [comment]
If we did want to switch to using `dial().number()` what changes would we need to make to get that working? For example, if I have my personal mobile device and want to also receive the calls made to the Twilio number `+15555555555`

**Comment by bchen-twilio** [comment]
To get the number on the phone ring, all you have to is to know the number and yes, use `dial().number()`.

**Comment by kjmacaul** [comment]
Do we need SIM cards from Twilio in order to receive the calls on device?

**Comment by kjmacaul** [comment]
I think my main question then is: "How do I tie a Twilio number to my personal device?"

**Comment by bchen-twilio** [comment]
As long as the callee's phone number is allowed under the Twilio Account SID, you are good to go! also the number your calling should be allowed under your Account Geo-permission (which I think should be true). Check out [this doc](https://www.twilio.com/docs/sip-trunking/voice-dialing-geographic-permissions) for more information about geo-permissions.

You don't really have to tie your personal number to be able receive the call on your personal phone, unless you want the caller to be only able to call a "Twilio" number and eventually ring the callee's number. Like my early comment, the "tie" should happen in your server logic and you are responsible to manage the relationship DB between numbers.

**Comment by kjmacaul** [comment]
We still aren't able to get the PSTN calls to ring on our devices. I'll try to walk you through exactly what we're doing and see if you can point out anything that looks wrong.

1. We purchased two Twilio numbers from the Twilio dashboard.
2. We assigned those numbers to users in our server's database.
3. The mobile app requests a Twilio Access Token from our server with the identity being the user's assigned phone number (15555555555 as an example).
4. The mobile app registers the given access token along with our VOIP push token through the TwilioVoice SDK.
5. Repeat steps 3 and 4 with another user (16666666666 for this user).
6. Place a call on the mobile app using the TwilioVoice SDK with "16666666666" as the "To" param.
7. Our server gets the request from Twilio asking for the TwiML and responds with `response.dial(callerId='15555555555').number('16666666666')`
8. The call rings on the caller device but the callee never receives a call.

**Comment by bchen-twilio** [comment]
Hi @kjmacaul 

In your DB there needs to be an association between `16666666666` and the real number (say `14151234567`), which is most likely a number (sim card) from the wireless providers, on the device. Since `16666666666` is only a Twilio number, `dial().number('16666666666')` won't really trigger the device with `14151234567` to ring. Instead you should be using `dial().number('14151234567')`.

-bobie

**Comment by kjmacaul** [comment]
Thank you. We were able to get calls using Twilio numbers working properly.
