### ISSUE TITLE
Quick start app calling another device not working

### ISSUE THREAD

**Issue by agreensh** [twilio/voice-quickstart-swift#160]
### Description

Running the quick start app, with no text in the entry field and press call. I get the recorded message as expected.

If I want to test calling another device, I did as in the README and changed the "identity", installed on 2nd device. Entered that text in the entry field on the 1st device, expecting it to call the 2nd device.

Exactly the same behaviour - just get the recorded message.
What am I missing?

Also, if I want to record the calls, how do I configure that?

#### Reproduces How Often

100%

#### Voice iOS SDK

2.0.6 via CocoaPods

#### Xcode

9.4.1

#### iOS Version

11.4.1

#### iOS Device

iPhone X and iPhone 8

**Comment by bchen-twilio** [comment]
Hi @agreensh 

We are pretty close and I think only thing we need to update is to update the URL of your TwiML application to the endpoint (`/makeCall` assuming you are using the Python quickstart) and make sure you are getting the correct parameters from the app when you make the outgoing call.

For this use case, you can trace your server endpoint and see if it is returning the TwiML that does `.client()` with the identity of the callee.

Let me know if this helps.
-bobie

**Comment by bchen-twilio** [comment]
Closing this issue since there hasn't been any activity for a while.
