### ISSUE TITLE
Error - 12300 Invalid Content-Type

### ISSUE THREAD

**Issue by Hamza123Imran** [twilio/voice-quickstart-swift#165]
Hi, i have implemented audio call in my iOS App with backend server of php. I'm getting the access token from the my server and than uses all the delegates , as per following the steps of twilio swift project. Now when i make a call, it successfully registered my push credentials first,  than on click of call button it first show ringing in my console and than call fails. When i check my voice dashboard on twilio i get this error, 
Twilio is unable to process the Content-Type of the provided URL. Please see the Twilio Markup XML Documentation for more information on valid Content-Types.
You must return a Content-Type for all requests. Requests without a Content-Type will appear in the Debugger as a 502 Bad Gateway error., These are the parameters that comes in the API, 
`

ApplicationSid | "APaecd77856d0049b8b80baa3c41f193a2"
-- | --
ApiVersion | "2010-04-01"
Called | ""
Caller | "client:alice"
CallStatus | "ringing"
to | "+923244544783"
From | "client:alice"
To | ""
CallSid | "CA98977f223a883f16b3585165066adde1"
Direction | "inbound"
AccountSid | "ACbc55b9853285730abd137444750e53c6"

I'm making client to client call through phone number. In identity i pass my phone number and in to i pass . other client phone number. I'm confused that why it is failing the call. Showing this error in my console, `[VERBOSE TVOCall] handlePJSIPInviteStateDisconnected. Error: Error Domain=com.twilio.voice.error Code=603 "Connection error (603)." UserInfo={NSLocalizedDescription=Connection error (603)., `

**Comment by Hamza123Imran** [comment]
Thanks for your quick response, we have checked that our TwiML have a <say> verb and some text in it. whenever we hit the Url from postman it gives us a call and that verb works and speaks the the text but the error comes only when we run the app and try to call. Can we provide you our URL that we are using for call and giving in our TwiML app? So that you can test it for us as we are unable to understand the problem.

**Comment by bchen-twilio** [comment]
Hi @Hamza123Imran 

I checked the Call SID again and from the error message I think you might want to check the URL provided in the TwiML application. It seems that you put the same link twice thus when the Twilio Voice service is trying fetch the TwiML, it tried to hit an URL that is in incorrect format.

-bobie

**Comment by bchen-twilio** [comment]
Hi @Hamza123Imran 

Directly to your last question, which i think should be the main goal for your app integrating the Voice iOS SDK: if you take a look at [makeCall.php](https://github.com/twilio/voice-quickstart-server-php/blob/master/makeCall.php) you will see to make a client-to-client call you can just use the `$dial->client($to);` line. The callee client needs to be registered with that identity to be able to receive the call notification (which I believe you already did) and accept the call-invite, then the audio should be flowing between the caller and callee once the call is connected.

**Comment by Hamza123Imran** [comment]
we have implemented makeCall.php on our server side, the code is in this link http://softdepth.com/projects/raven/customer/audiocall with to,from,token params. When we hit this url on postman we receive call with the same message that is written in TwiML xml file. 

Now when we hit the this method in ios app

let parameteres =  ["To" : otherUserNumber,
                            "Caller" : myPhoneNumber,
                            "From" : myPhoneNumber,
                            "from" : myPhoneNumber!,
                            "to" : otherUserNumber
                            ]
        print(uuid)
        
        print(parameteres)
        call = TwilioVoice.call(accessToken!, params:parameteres as? [String : String] , uuid:uuid, delegate: self)
        print(call!)
        self.callKitCompletionCallback = completionHandler

it query on Twilio server starts ringing and after couple of seconds it show error and the error comes in our Twilio Debugger console. 

Can you please help in setting up the flow of call from ios to ios app if we are missing something? and guide us in details how Twilio call works and how we have to make our TwiML to make a simple call with Twilio VOIP? may be we are unable to understand the proper flow. We are stuck here and our work is pending. Kindly help us in understanding the documentation for us, its a bit confusing.

**Comment by bchen-twilio** [comment]
Hi @Hamza123Imran 

Sorry for the delay.
I checked the Account SID and for some reason I still saw couple of errors (2018/9/18) indicating that the URL specified in the Voice incoming request doesn't seem to be correct.
Also if you believe the response from your `makeCall.php` endpoint is correct, the response should look like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial callerId="14081234567">
        <Client>bobie</Client>
    </Dial>
</Response>
```

Let me know if this helps.
-bobie

**Comment by Hamza123Imran** [comment]
Hi i have check my url for makecall on postman it is showing me same response as you said above,
[https://prnt.sc/kyddm7](url)

But when this url is hit in voice dashboard we get content type error, why it is not showing same response in voice dashboard?

We Follow up following steps
1) Audio token generated from PHP API here is screenshot how we are generating audio token 
[http://prntscr.com/kydp1s](url)
2) After getting token from PHP we are calling voice delegate in IOS please check screen shot 
[http://prntscr.com/kydpz6](url)
3) Twillio App hit makeCall API which mention here http://prntscr.com/kydrq6
4) And makeCall API returning correct response http://prntscr.com/kydsf2
5) here is the code inside makeCall API function http://prntscr.com/kydt58
Now where the actual mistake we are doing can you identify that?

**Comment by Hamza123Imran** [comment]
Hi i have check my url for makecall on postman it is showing me same response as you said above,
We Follow up following steps
1) Audio token generated from PHP API here is screenshot how we are generating audio token http://prntscr.com/kydp1s
2) After getting token from PHP we are calling voice delegate in IOS please check screen shot http://prntscr.com/kydpz6
3) Twillio App hit makeCall API which mention here http://prntscr.com/kydrq6
4) And makeCall API returning correct response http://prntscr.com/kydsf2
5) here is the code inside makeCall API function http://prntscr.com/kydt58
Now can you identify that where we are making mistake? Because response on postman is right but when hit on voice dashboard it shows content type error?

**Comment by bchen-twilio** [comment]
Closing this issue for now. @Hamza123Imran please feel free to re-open or create a new issue in the future.

Thanks,
-bobie
