### ISSUE TITLE
Error: Error Domain=com.twilio.voice.error Code=603 "Connection error (603)

### ISSUE THREAD

**Issue by Hamza123Imran** [twilio/voice-quickstart-swift#167]
Hi, i'm implementing twilio voice call in my ios app, i have php backend of my own. I got accessToken correct. When i call it shows me call status ringing and than call fails with this error, 
`[VERBOSE TVOCall] handlePJSIPInviteStateDisconnected. Error: Error Domain=com.twilio.voice.error Code=603 "Connection error (603)." UserInfo={NSLocalizedDescription=Connection error (603)., NSLocalizedFailureReason=Connection error.` I have searched for this error but didn't find any solution. What this error says?

**Comment by bchen-twilio** [comment]
Hi @Hamza123Imran 

Can you provide a Call SID with which you saw the `603` error? You should be able to find the Call SID in your IDE console or in the Programmable Voice Dashboard: https://www.twilio.com/console/voice/dashboard

Thanks
-bobie

**Comment by Hamza123Imran** [comment]
This is the Call SID `CA9f9c05df89f415a5e6c2617e881b2e4a`. When does this error means?

**Comment by bchen-twilio** [comment]
Hi @Hamza123Imran 

I've run the Call SID and got this
```
Twilio attempted to retrieve content from the URL http://softdepth.com/projects/raven/customer/audiocallhttp://softdepth.com/projects/raven/customer/audiocall but was unable to process the application/json Content-Type header in the response. Please see the Twilio XML Markup Documentation for more details on valid Content-Type settings.
```
You are using the server helper library provided for TwiML generation, right?

**Comment by Hamza123Imran** [comment]
Yeah, this url is use for TwiML . Why it always shows this error? Where this content type is going wrong?

**Comment by bchen-twilio** [comment]
Can you update the Voice URL of the TwiML app (in the Twilio Console) with just `http://softdepth.com/projects/raven/customer/audiocall` and see if it works?

**Comment by Hamza123Imran** [comment]
I have changed with this url now i'm not getting that error, but call is still failing. This error is shown in console. `EndCallAction transaction request failed: The operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 4.` What is this for?

**Comment by bchen-twilio** [comment]
If you take a look at the transaction error definition CallKit framework, `error 4` means that the UUID passed as long with the request is invalid, most likely different from the one used for reporting the new call.

**Comment by Hamza123Imran** [comment]
I have debug my code and check the all the uuid where i'm passing in the code. The uuid is going fine in all the delegates. Even when i report the new call the uuid goes correct and call again fails with same error and this `PJSIP(4):   pjsua_core.c  .PJSUA destroyed...`

**Comment by Hamza123Imran** [comment]
Is the content type coming in the above url is right? Because error in voice dashboard is referring towards the content Type.

**Comment by Hamza123Imran** [comment]
I have check my uuid before making a call and also checked it after making a call in this delegate,
`func performEndCallAction(uuid: UUID) {

        let endCallAction = CXEndCallAction(call: uuid)
        let transaction = CXTransaction(action: endCallAction)
        print(endCallAction)
        print(transaction)
        callKitCallController.request(transaction) { error in
            if let error = error {
                NSLog("EndCallAction transaction request failed: \(error.localizedDescription).")
                TwilioVoice.logLevel = TVOLogLevel.verbose
                TwilioVoice.setModule(TVOLogModule.PJSIP, logLevel: TVOLogLevel.verbose)
                return
            }

            NSLog("EndCallAction transaction request successful")
        }
    }` in both cases my uuid is going same, nothing is change. Than why this issue is till coming?

**Comment by bchen-twilio** [comment]
Closing this issue assuming the original issue has been resolved by the updates in [this pull request](https://github.com/twilio/voice-quickstart-swift/pull/171).
@Hamza123Imran please feel free to reopen the ticket if you are still running into the same issue with the fix.

Thanks,
-bobie
