### ISSUE TITLE
Deprecation Notice - Versions 2.0.0-beta9 to 2.0.0-beta12

### ISSUE THREAD

**Issue by mrchauhan2802** [twilio/voice-quickstart-swift#170]
Deprecation Notice - Versions 2.0.0-beta9 to 2.0.0-beta12

For which reason it is ?

For this i have to update code ??

and if yes then how ?

**Comment by bchen-twilio** [comment]
Hi @mrchauhan2802 

We used an SSL certificate in versions from `2.0.0-beta9` to `2.0.0-beta12` and the certificate has been deprecated. Applications using these versions won't be able to perform (un)registration successfully. For apps using the latest version of the Voice 2.0 SDK should not be affected by this notice.

-bobie

**Comment by mrchauhan2802** [comment]
Thanks
