### ISSUE TITLE
How to keep the default system screen call

### ISSUE THREAD

**Issue by sa7bi** [twilio/voice-quickstart-swift#172]
### Description

Hi,

I'm using the source code of this repository to understand how Twilio Voice and Callkit works in hope of implementing it in my own app.

With incoming calls, the system screen is show to accept or decline the call. When accepted, the system call screen is hidden and the main layout of the app is shown. Is there a way, to keep the system screen as with normal calls instead ??

Thanks

**Comment by bchen-twilio** [comment]
Hi @sa7bi 

Thanks for choosing the Twilio Voice SDK.
There seems to be other developers who are also interested in the same topic but looks like you can only stay in the system Call app when the call is answer while the phone is locked: https://stackoverflow.com/questions/43027343/how-to-keep-ios-native-call-ui-after-answering-the-call-with-callkit

**Comment by bchen-twilio** [comment]
Hi @sa7bi
I'll close this issue for now but please feel free to reach out to us if you run into any issue or question in the future.

Cheers,
-bobie
