### ISSUE TITLE
Getting issue when client accept the Voip Call

### ISSUE THREAD

**Issue by devlove1C** [twilio/voice-quickstart-swift#178]
Hello Team, 
I need help, I want to start a call timer, when user accept or answered the call.Actually currently i am able to connect the voip call, but not able to track when user accept the call.
Please let me know which method will call when user accept the call or answer the call. 
I am using xcode 10.0
and latest version of Twilio.
I have used the demo call.
Please let me know what i do?

**Comment by bchen-twilio** [comment]
Hi @devlove1C 

Thanks for reaching out and glad that you are able to integrate the Voice iOS SDK and make calls!
To do this, you can use the [answerOnBridge flag in your TwiML response](https://www.twilio.com/docs/voice/twiml/dial#answeronbridge) and configure according to your business logic. If the flag is set to `true`, the caller client will only get the `callDidConnect:` delegate callback when the call is actually answered by the receiver.

Let us know if the flag works for you.
Thanks
-bobie

**Comment by devlove1C** [comment]
Hello Team,
Actually currently when phone ringing start, the callDidConnect: delegate method called but  this method doesn't  call when the call is actually answered by the receiver.

We have already implement the below method at back end side 

const VoiceResponse = require('twilio').twiml.VoiceResponse;
const response = new VoiceResponse();
const dial = response.dial({
  callerId: '+15551112222',
});
dial.number('+15558675310');

console.log(response.toString());

Please let me know what I do, to track the call is answered by the receiver.
Thanks Dev

**Comment by bchen-twilio** [comment]
Hi @devlove1C 

Please add `answerOnBridge` to your `dial()` so that your mobile client gets the `callDidConnect:` callback when the call is answered by the callee.

**Comment by devlove1C** [comment]
Hello @bchen-twilio 

I have added the 'answerOnBridge' in dial(), but still doesn't get callback when the call is answered by the callee.
Here is my code :- 

<?xml version="1.0" encoding="UTF-8" ?>
<Response>
    <Dial callerId="+12138103667" answerOnBridge="true"
  timeLimit="14400" timeout="15" action="https://10398:a52aa0d8-0548-45a9-963c-e6bf8f3fac92@ssoni.pagekite.me/PE.Telephony.Web/voipstatus">
        <Number statusCallback="https://10398:a52aa0d8-0548-45a9-963c-e6bf8f3fac92@ssoni.pagekite.me/PE.Telephony.Web/voipstatus"  statusCallbackMethod="POST" statusCallbackEvent="initiated ringing answered completed">+918269009410</Number>
    </Dial>
</Response>

I have attached the .swift file(swift code which we are using to voip call) Please check that
Let me know if there is anything missing or wrong
Thanks 
-Dev

**Comment by bchen-twilio** [comment]
Hi @devlove1C 

Unfortunately I cannot view those file for security reasons. It would be great if you can share the snippets in Github gist format. We can check the TwiML response if you can give us a Call SID.
Back to the issue you were seeing - did it stop giving you the `callDidConnect:` callback after you enabled `answerOnBridge` in the `<Dial>`?

Thanks
-bobie

**Comment by devlove1C** [comment]
Hello @bchen-twilio ,
Actually I want to make a phone call by VOIP. We have a app, in which we want voip call implementation. User can able to make a voip call  by app and  callee will get a phone call on his mobile number.
**Server side code is**

```
<?xml version="1.0" encoding="UTF-8" ?>
<Response>
    <Dial callerId="+12138103667" answerOnBridge="true"
  timeLimit="14400" timeout="15" action="https://10398:a52aa0d8-0548-45a9-963c-e6bf8f3fac92@ssoni.pagekite.me/PE.Telephony.Web/voipstatus">
        <Number statusCallback="https://10398:a52aa0d8-0548-45a9-963c-e6bf8f3fac92@ssoni.pagekite.me/PE.Telephony.Web/voipstatus"  statusCallbackMethod="POST" statusCallbackEvent="initiated ringing answered completed">+918269009410</Number>
    </Dial>
</Response>
```

**And my swift code is here** 
import UIKit
import TwilioVoice
import PushKit
import CallKit
import AVFoundation

class HomeVC: UIViewController,PKPushRegistryDelegate , TVONotificationDelegate, CXProviderDelegate,TVOCallDelegate {
    var token_info: UserTokenResponse!
     @IBOutlet weak var shadowView: UIView!
    @IBOutlet weak var CallPopupView: UIView!
    @IBOutlet weak var txtUserName: UITextField!
    @IBAction func dismissCallpopupView(_ sender: Any) {
        CallPopupView.isHidden = true
        shadowView.isHidden = true
        txtUserName.resignFirstResponder()
    }
    
    @IBAction func showCallPopup(_ sender: Any) {
        shadowView.isHidden = false
         CallPopupView.isHidden = false
    }
    // MARK: PKPushRegistryDelegate
    func pushRegistry(_ registry: PKPushRegistry, didUpdate credentials: PKPushCredentials, for type: PKPushType) {
        NSLog("pushRegistry:didUpdatePushCredentials:forType:")
        let deviceToken = (credentials.token as NSData).description
        
        if (token_info != nil) {
            TwilioVoice.register(withAccessToken: token_info.token, deviceToken: deviceToken) { (error) in
                if let error = error {
                    NSLog("An error occurred while registering: \(error.localizedDescription)")
                }
                else {
                    NSLog("Successfully registered for VoIP push notifications.")
                }
            }
        }
        
        
        self.deviceTokenString = deviceToken
    }

    // MARK: TVONotificaitonDelegate
    func callInviteReceived(_ callInvite: TVOCallInvite) {
        if (callInvite.state == .pending) {
           // handleCallInviteReceived(callInvite)
        } else if (callInvite.state == .canceled) {
           // handleCallInviteCanceled(callInvite)
        }
    }

    
    func notificationError(_ error: Error) {
        NSLog("notificationError: \(error.localizedDescription)")
    }
    
    // MARK: CXProviderDelegate
    func providerDidReset(_ provider: CXProvider) {
        NSLog("providerDidReset:")
        TwilioVoice.isAudioEnabled = true
    }
    
    @IBOutlet weak var placeCallButton: UIButton!
     var call:TVOCall?

    var voipRegistry:PKPushRegistry
     var deviceTokenString:String?
    var isSpinning: Bool
    var incomingAlertController: UIAlertController?
    var callKitCompletionCallback: ((Bool)->Swift.Void?)? = nil
    
    
    let callKitProvider:CXProvider
    let callKitCallController:CXCallController
    
      @IBOutlet weak var callControlView: UIView!
    @IBOutlet weak var muteSwitch: UISwitch!
    @IBOutlet weak var speakerSwitch: UISwitch!
    
    required init?(coder aDecoder: NSCoder) {
        isSpinning = false
        voipRegistry = PKPushRegistry.init(queue: DispatchQueue.main)
        TwilioVoice.logLevel = .verbose
        let configuration = CXProviderConfiguration(localizedName: "CallKit Quickstart")
        configuration.maximumCallGroups = 1
        configuration.maximumCallsPerCallGroup = 1
        configuration.ringtoneSound = "ringtone.caf" //set your default ringtone
        if let callKitIcon = UIImage(named: "iconMask80") {
            configuration.iconTemplateImageData = UIImagePNGRepresentation(callKitIcon)
        }
        
        callKitProvider = CXProvider(configuration: configuration)
        callKitCallController = CXCallController()
        
        super.init(coder: aDecoder)
        
        callKitProvider.setDelegate(self, queue: nil)
        
        voipRegistry.delegate = self
        voipRegistry.desiredPushTypes = Set([PKPushType.voIP])
    }
    
    deinit {
        // CallKit has an odd API contract where the developer must call invalidate or the CXProvider is leaked.
        callKitProvider.invalidate()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        let data = UserDefaults.standard.object(forKey: "USER") as! NSData
        let user_info = NSKeyedUnarchiver.unarchiveObject(with: data as Data) as! PsychicLoginResponse
        let token_data = UserDefaults.standard.object(forKey: "TOKEN_INFO") as! NSData
       token_info = NSKeyedUnarchiver.unarchiveObject(with: token_data as Data) as! UserTokenResponse
       // let paraTo : String = user_info.firstName + "\(user_info.customerId)"
        self.title = user_info.firstName
       toggleUIState(isEnabled: true, showCallControl: false)
    }
    //MARK:- Mute Switch Toggle
    @IBAction func muteSwitchToggled(_ sender: UISwitch) {
        if let call = call {
            call.isMuted = sender.isOn
        } else {
            NSLog("No active call to be muted")
        }
    }
    //MARK:- Speaker Switch Toggle
    @IBAction func speakerSwitchToggled(_ sender: UISwitch) {
        toggleAudioRoute(toSpeaker: sender.isOn)
    }

    func toggleUIState(isEnabled: Bool, showCallControl: Bool) {
       // placeCallButton.isEnabled = isEnabled
        if (showCallControl) {
            callControlView.isHidden = false
            muteSwitch.isOn = false
            speakerSwitch.isOn = true
         }else {
            callControlView.isHidden = true
        }
    }

    @IBAction func placeCall(_ sender: UIButton) {
        txtUserName.resignFirstResponder()
         TwilioVoice.call( token_info.token, params: ["to" : txtUserName.text!], delegate: self)

    }
    
    
    // MARK: Call Kit Actions
    // MARK: Call Kit Actions
    func performStartCallAction(uuid: UUID, handle: String) {
        let callHandle = CXHandle(type: .generic, value: handle)
        let startCallAction = CXStartCallAction(call: uuid, handle: callHandle)
        let transaction = CXTransaction(action: startCallAction)
        
        callKitCallController.request(transaction)  { error in
            if let error = error {
                NSLog("StartCallAction transaction request failed: \(error.localizedDescription)")
                return
            }
            NSLog("StartCallAction transaction request successful")
            let callUpdate = CXCallUpdate()
            callUpdate.remoteHandle = callHandle
            callUpdate.supportsDTMF = true
            callUpdate.supportsHolding = true
            callUpdate.supportsGrouping = false
            callUpdate.supportsUngrouping = false
            callUpdate.hasVideo = false
            self.callKitProvider.reportCall(with: uuid, updated: callUpdate)
        }
    }
    
    
    func stopSpin() {
        isSpinning = false
    }
    
    
    // MARK: TVOCallDelegate
    func callDidConnect(_ call: TVOCall) {
        NSLog("callDidConnect:")
        self.call = call
        toggleUIState(isEnabled: true, showCallControl: true)
        stopSpin()
        toggleAudioRoute(toSpeaker: true)
    }
    
    func call(_ call: TVOCall, didFailToConnectWithError error: Error) {
        NSLog("Call failed to connect: \(error.localizedDescription)")
        
        if let completion = self.callKitCompletionCallback {
            completion(false)
        }
        
        performEndCallAction(uuid: call.uuid)
        callDisconnected()
    }
    
    func call(_ call: TVOCall, didDisconnectWithError error: Error?) {
        if let error = error {
            NSLog("Call failed: \(error.localizedDescription)")
        } else {
            NSLog("Call disconnected")
        }
        
        performEndCallAction(uuid: call.uuid)
        callDisconnected()
    }
    
    func callDisconnected() {
        self.call = nil
        self.callKitCompletionCallback = nil
        stopSpin()
        toggleUIState(isEnabled: true, showCallControl: false)
        self.placeCallButton.setTitle("Call", for: .normal)
    }
    func performEndCallAction(uuid: UUID) {
        
        let endCallAction = CXEndCallAction(call: uuid)
        let transaction = CXTransaction(action: endCallAction)
        
        callKitCallController.request(transaction) { error in
            if let error = error {
            self.CallPopupView.isHidden = true
                NSLog("EndCallAction transaction request failed: \(error.localizedDescription).")
                return
            }
            NSLog("EndCallAction transaction request successful")
        }
    }
    
    // MARK: AVAudioSession
    func toggleAudioRoute(toSpeaker: Bool) {
        // The mode set by the Voice SDK is "VoiceChat" so the default audio route is the built-in receiver. Use port override to switch the route.
        do {
            if (toSpeaker) {
                try AVAudioSession.sharedInstance().overrideOutputAudioPort(.speaker)
            } else {
                try AVAudioSession.sharedInstance().overrideOutputAudioPort(.none)
            }
        } catch {
            NSLog(error.localizedDescription)
        }
    }
    
    func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType) {
        NSLog("pushRegistry:didReceiveIncomingPushWithPayload:forType:")
        if (type == PKPushType.voIP) {
            TwilioVoice.handleNotification(payload.dictionaryPayload, delegate: self)
        }
    }
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }

Note:- Let me know if there is anything missing or wrong

**Comment by devlove1C** [comment]
Hello team, 
Can anybody have idea about my above comment issue. 
Please let me know what i do?

**Comment by bchen-twilio** [comment]
Hi @devlove1C 

Before I use the same TwiML logic and try, are you getting any `callDidConnect:` callback with this implementation (and when)?

Thanks
-bobie

**Comment by devlove1C** [comment]
Hello @bchen-twilio 
Yeah when phone ringing start, the callDidConnect: delegate method called but this method doesn't call when the call is actually answered by the receiver.
I didn't undertstand what you want to say about "TwiML logic"
Please response as soon as possible

**Comment by bchen-twilio** [comment]
Hi @devlove1C 

The `callDidConnect:` callback will only be fire once, either the call is connected between the caller and Twilio Voice service, or the call is answered by the callee with `answerOnBridge` enabled in the TwiML. Do you experience the same when the callee is another SDK client, i.e. using `<Client>` inside `<Dial>` and call another registered identity?

Also it would be great if you can provide us a Twilio Call SID which you had this issue? That way we can also investigate more insights of the signaling connection of the call. You can find Call SIDs in the [Programmable Voice Dashboard](https://www.twilio.com/console/voice/dashboard).

Thanks,
-bobie

**Comment by bchen-twilio** [comment]
Hi @devlove1C 

I am closing the issue since there hasn't been any activity for a while. Feel free to reach out to us any time.

Thanks
-bobie

**Comment by AdnanMajeed06** [comment]
Hi, 
i'm facing the same issue mentioned above. @bchen-twilio can you please help out where to add `answerOnBridge` . I've downloaded php code and don't know in which file add this `answerOnBridge`

**Comment by bchen-twilio** [comment]
Hi @AdnanMajeed06 

You can use the `setAnswerOnBridge` method of the `Dial` object: https://github.com/twilio/twilio-php/blob/650f42647c9b3039e03ae075785164ec97203e94/src/Twilio/TwiML/Voice/Dial.php#L202

Let me know if this works for you.

Cheers,
-bobie

**Comment by AdnanMajeed06** [comment]
Hi @bchen-twilio 
Thank for your quick reply. 
I've downloaded the sample PHP code from here
https://github.com/twilio/voice-quickstart-server-php
Can you please help me how I can add `setAnswerOnBridge ` in makeCall.php file.

Thank you

**Comment by bchen-twilio** [comment]
Hi @AdnanMajeed06 

This will do:
```
```

**Comment by AdnanMajeed06** [comment]
Hi @bchen-twilio ,

I've already tried this above code but it seems not working. `callDidStartRinging` never called and `callDidConnect` delegate called when call start ringing. When callee answer the call. There is no delegate that triggers.
Please check the code.

``` include('./vendor/autoload.php');
include('./config.php');
$callerId = $_POST["from"] ;
$to = isset($_POST["to"]) ? $_POST["to"] : "";
if (!isset($to) || empty($to)) {
  $to = isset($_GET["to"]) ? $_GET["to"] : "";
}
$callerNumber = '1234567890';
$response = new Twilio\Twiml();
if (!isset($to) || empty($to)) {
  $response->say('How are you');
} else if (is_numeric($to)) {
  $dial = $response->dial(
    array(
  	  'callerId' => $callerNumber
  	));
  $dial->number($to);
} else {
  $dial = $response->dial(
      array(
          'callerId' => $callerId,
          'answerOnBridge' => TRUE
      ));
  $dial->client($to);
}
print $response;
```

Thank you

**Comment by bchen-twilio** [comment]
Hi @AdnanMajeed06 

Please provide a Call SID where you are experiencing problem with the callbacks.

**Comment by AdnanMajeed06** [comment]
Hi @bchen-twilio ,
Here is SID
AC2ad3a65553e8e1e6ef7d9f12f85fecba

Thanks

**Comment by AdnanMajeed06** [comment]
Hi @bchen-twilio 

There are two SID i'm using in Config file. i don't know which one is Call SID. i'm providing you both.

`$APP_SID = 'APb32af4b29cc4035bf37415f641668b4f';`
`$ACCOUNT_SID = 'AC2ad3a65553e8e1e6ef7d9f12f85fecba';`

Thanks

**Comment by bchen-twilio** [comment]
Hi @AdnanMajeed06 

You can find the Call SIDs here: https://www.twilio.com/console/voice/calls/logs

**Comment by AdnanMajeed06** [comment]
@bchen-twilio 

Here is call SID : `CAef7ae541408a46f3c202c0d59034f894`

Thank you

**Comment by bchen-twilio** [comment]
Thanks for providing the Call SID. I've checked it and for some reason during the signaling handshaking process I couldn't find the event that would trigger the ringing event. I will reach out to the Voice backend experts and see if they can provide more insights and will keep you updated.

-bobie

**Comment by bchen-twilio** [comment]
Hi @AdnanMajeed06 

According to our backend expert, the account is currently a trial account thus once the call is made, the Twilio Voice service will skip the ringing state and connect the call directly to play a promotion prompt. That's the reason why the app didn't receive the `callDidStartRinging:` callback.

Can you confirm this?

Thanks,
-bobie

**Comment by AdnanMajeed06** [comment]
Hi @bchen-twilio,

Yes currently I'm using trial account and this point was never mentioned before neither in document that `callDidStartRinging` or `answerOnBridge` will not work in trial account. That can save our time :) 
I'll upgrade my account and then let you know. 
Thank you so much for your help. 
Cheers.

**Comment by AdnanMajeed06** [comment]
Hi @bchen-twilio ,
I've updated my account and `callDidStartRinging` callback called. But I've got another issue here :)

There is no call ringing tone. In trial version once promotion prompt end there was a rigning tone. But now I can't hear any tone from the caller side.
Here is my latest call SID :  `CA20f1b1a619d2d43d1ce3dd2db309a843`

Thanks

**Comment by bchen-twilio** [comment]
Hi @AdnanMajeed06 

With `answerOnBridge` enabled with the <Dial> verb, the caller won't hear any ringtone. The application can play the custom ringtone file locally upon receiving the `callDidStartRinging:` callback and stop when the call is connected or disconnected.

-bobie

**Comment by MarkPare** [comment]
I lost a day to this because no where in the docs does it say this is a limitation of trial accounts. At the least, it would be helpful to drop that info here as a bullet point: https://support.twilio.com/hc/en-us/articles/360036052753-Twilio-Free-Trial-Limitations.

**Comment by bobiechen-twilio** [comment]
Hi @MarkPare 

Thanks for reaching out and we are sorry for the inconvenience. Can you provide a Call SID or the error details to help us improve the SDK documentation?

-bobie
