### ISSUE TITLE
Use Voice quick start using programmable voice 

### ISSUE THREAD

**Issue by VDPurohit** [twilio/voice-quickstart-swift#180]
Hello there ,

First,Is it possible to voice call between user A and user B using Programmable chat and both are use iOS chat App(means user A and User B both are use my app for voice call)?

I download voicequicktstart demo an configure for client to client call(both user in iOS Devices) my whole things as shown bellow 

let baseURLString = "http://localhost/voicequickstartserver/"
// If your token server is written in PHP, accessTokenEndpoint needs .php extension at the end. For example : /accessToken.php
let accessTokenEndpoint = "accessToken.php"
let identity = "alice"
let twimlParamTo = "to"

then after change for client to client calling on other device like 

let baseURLString = "http://localhost/voicequickstartserver/"
// If your token server is written in PHP, accessTokenEndpoint needs .php extension at the end. For example : /accessToken.php
let accessTokenEndpoint = "accessToken.php"
let identity = "bob"
let twimlParamTo = "to"

then after I call bob from use Alice it's ringing then after voice like "we are sorry application error occurred,Good bye!",And incoming call alert or any other event shown at receiver side

and also see the console data like below image there is no to value 

![screen shot 2018-10-10 at 3 17 07 pm](https://user-images.githubusercontent.com/33477514/46728107-b4ccff00-cc9f-11e8-9a21-2037ca30c186.png)

and when make call url(http://localhost/voicequickstartserver/makeCall.php?to=123) hit in browser It shows
![screen shot 2018-10-10 at 3 25 09 pm](https://user-images.githubusercontent.com/33477514/46728609-d2e72f00-cca0-11e8-8e1f-7a442e7f179c.png)

please help as much as your earliest,
Thanks

**Comment by bchen-twilio** [comment]
Hi @VDPurohit 

Did you mean the Programmable Chat iOS SDK or Programmable Voice iOS SDK by "Programmable chat"?
For the error message you heard, most likely the `makeCall.php` endpoint is not returning a valid TwiML response. Can you provide us the Call SID so that we can investigate the root cause of the failure?

Thanks
-bobie

**Comment by VDPurohit** [comment]
@bchen-twilio  Thanks for response

Here I attached my Call SID and sample of call response

CallSID:-"CA0b8ace8a0b2ba890d47859db250451fd"

2018-10-11 10:50:18.000518+0530 SwiftVoiceQuickstart[1483:441742] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 9;
    "audio_level_out" = 85;
    "call_sid" = CA0b8ace8a0b2ba890d47859db250451fd;
    jitter = "7.25";
    mos = "4.43";
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 51;
    rtt = 0;
    timestamp = "2018-10-11T10:50:17.999+05:30";
    "timestamp_ms" = 1539235217998;
    "total_bytes_received" = 23200;
    "total_bytes_sent" = 24000;
    "total_packets_lost" = 1;
    "total_packets_received" = 145;
    "total_packets_sent" = 150;
}

and when http://localhost/voicequickstartserver/makeCall.php?to=123 run in browser which is previous message with screen shot
my twilio account is trial for testing.

Thanks

**Comment by bchen-twilio** [comment]
Hi @VDPurohit 

I've run the Call SID and found that in you TwiML app settings, URLs with internal IP address are used. Please use public accessible URLs for your TwiML apps. You can follow the [PHP guide](https://github.com/twilio/voice-quickstart-server-php#up-and-running) to set up a server using ngrok.

Thanks
-bobie

**Comment by VDPurohit** [comment]
@bchen-twilio 

Thanks a lot man it's working fine.Closed it

thanks again :D
