### ISSUE TITLE
Programmable Voice information

### ISSUE THREAD

**Issue by VDPurohit** [twilio/voice-quickstart-swift#182]
Hello there,

I have some question related to call like:-

1.Can we chat during calls (one to one and Group chat)?
2.Twilio provide call history?
3.Can record a call when conversation already started or supported from begins?
4. Can we join user as observer without participant?

Thanks

**Comment by bchen-twilio** [comment]
Hi @VDPurohit 

- Do you mean using the Programmable Chat SDK during a call using the Voice SDK?
- Yes, you go to the [Call Logs page](https://www.twilio.com/console/voice/calls/logs) and find out the history and status of the calls.
- You can specify `record` flag in the TwiML. This can only be configured before starting a call.
- You can connect a mobile client to a call (p2p or conference) and mute the local audio.

cheers
-bobie

**Comment by VDPurohit** [comment]
@bchen-twilio 

thanks for response 

Create Client to Client chat App:-

1. Do you mean using the Programmable Chat SDK during a call using the Voice SDK?
- Yes,chat(One to one and Group) during voice call SDK as well as Programmable Video.

2. For call logs i see that in console but can I saw the user vice history in Mobile App?

Thanks

**Comment by VDPurohit** [comment]
@bchen-twilio 

It's my owner to chat with you(Please closed it),
Thanks.

**Comment by VDPurohit** [comment]
@bchen-twilio 

Hello,
Any Update?

**Comment by bchen-twilio** [comment]
Hi @VDPurohit 

You PHP endpoint can definitely generate different type of responses (one to one or conference call) based the values of the request parameters.
Currently the mobile SDK does not have API to provide quality feedback but you can either write a URL-based utility module in the application or set up an endpoint in your server to handle and submit the feedback data to the Twilio quality feedback API.

-bobie

**Comment by VDPurohit** [comment]
@bchen-twilio  thanks 
👍
