### ISSUE TITLE
Incoming call works only with the first device with id - 'alice'

### ISSUE THREAD

**Issue by Ankish** [twilio/voice-quickstart-swift#186]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Voice SDK Guides](twilio.com/docs/api/voice-sdk)
>  * [GitHub Issues](https://github.com/twilio/voice-quickstart-swift/issues)
>  * [Changelog](https://www.twilio.com/docs/api/voice-sdk/ios/changelog)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

I have followed the sample for iOS sdk, node.js latest. I setup the first device as 'alice' that device works fine with 'alice' identifier. All the other devices I am able to make calls but only that device and with 'alice' identifier receives the call. I have checked the access token with JWT , identifier is correct. On the server with ngrok it says calling client 'XXX' ,

APP_SID= "AP74700b32d3f797e0ffbeb0ca37c48dda"

In twilio logs:
Error - 52004
Credential SID not specified

But its working fine for device with Alice, not others.
Really puzzled. Kindly help.

### Steps to Reproduce

Steps 

#### Expected Behavior

Should connect call

#### Actual Behavior

Call not connecting with other devices and identifier than alice

#### Reproduces How Often

Everytime

#### Logs

```
If a client makes a call to alice (first device which was registered with name alice) - it succeeds.
Server logs

not a number
Response:
<?xml version="1.0" encoding="UTF-8"?><Response><Dial callerId="client:quick_start"><Client>alice</Client></Dial></Response>


If a client makes a call to anyother device with a different id it fails.

#
not a number
Response:<?xml version="1.0" encoding="UTF-8"?><Response><Dial callerId="client:quick_start"><Client>keta</Client></Dial></Response>
#

func call(_ call: TVOCall, didDisconnectWithError error: Error?) is called with nil error at the calling endpoint.
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

[ 2.0.7 via CocoaPods]

#### Xcode

Xcode 10

#### iOS Version

iOS 11 and 12

#### iOS Device

iOS 7 its working, iOS 6s its not. I dont think it should be linked to device.

**Comment by bchen-twilio** [comment]
Hi @Ankish 

Thanks for reporting the issue and it does look odd that you are getting the `Credential SID not specified` error message.
Can you provide us a Call SID of a call which failed to reach to the client identity that you are trying to call?

Thanks
-bobie

**Comment by Ankish** [comment]
Initially this scenario was not working, But currently, none of the uses cases work, I reached out to the support and it seems there is a bug on the backend which is causing that. Its being tracked at ticket # 1558924 . This might be related to that aswell.

**Comment by bchen-twilio** [comment]
Hi @Ankish 

I've used your account SID and found that there was no new errors since October 28th and the last error was indicating the URL of the TwiML application is not available.
Not sure if that's problem but I found that inside your Access Token in the support ticket #1558924, there are multiple `\` characters at the end of the credentials. Can you update the token endpoint to remove the `\`s and try again?

Thanks
-bobie

**Comment by bchen-twilio** [comment]
Hi @Ankish 

I am closing this ticket and assuming that the original issue has been resolved and things are working great with your application. Please feel free to reopen or create a new issue if you run into any.

Thanks
-bobie
