### ISSUE TITLE
iOS lock screen - Mute call

### ISSUE THREAD

**Issue by OmerAI** [twilio/voice-quickstart-swift#187]
### Description

I Can't mute call on iOS lock screen.

Also, can someone please explain what are the limitations of receiving calls when iPhone is locked?

### Steps to Reproduce

1. Receive a call.
2. Click on Mute.
#### Expected Behavior

The call should be muted.

#### Actual Behavior

The call isn't muted.

#### Reproduces How Often

All the time.

#### Voice iOS SDK

TwilioVoice v2.0.7

#### Xcode

10

#### iOS Version

12.0

#### iOS Device

iPhone X

**Comment by bchen-twilio** [comment]
Hi @OmerAI 

Did you see any error when you tried to mute the call? and by "lock screen" did you mean in the system Call application?
There is no limitation to receiving or answering calls when the phone is locked. There is a known issue that is blocking the application to show the incoming call in the CallKit UI and the workaround is to either initialize the `PkPushRegistry` in a global queue or use the `pushRegistry:didReceiveIncomingPushWithPayload:forType:` method which does not have the completion callback .

Hope this helps.
-bobie

**Comment by OmerAI** [comment]
Thanks fo the reply.

I don't see an error. When I tap on the Mute button it will not mute the call.
FYI - when an iOS device is locked the call is answered by the iOS call screen.

The limitation I'm talking about is how can I mute the call if I don't have any indication that user clicked on the mute button?

**Comment by bchen-twilio** [comment]
Hi @OmerAI 

If you have CallKit integrated in your application, you should receive the `provider:performSetMutedCallAction:` delegate callback when the user mutes the call from the system call UI, and then you can decide the action based on the value of the parameter.

-bobie

**Comment by OmerAI** [comment]
Thanks that sounds right....
