### ISSUE TITLE
Related to voIP call

### ISSUE THREAD

**Issue by VDPurohit** [twilio/voice-quickstart-swift#188]
Hello there,

I setup my server and calling works fine when app is running but when I try to kill or terminate my app voice call not arrived at receiver side but ringing  from sender side.I already generate and setup voIP certificate from mine side but I it isn't working at the time app is terminated or close(Kill) condition.I was trying using both callKit as well as quickStart without callKit demo?

Any thing I forgot,
Please help me,Thanks

**Comment by bchen-twilio** [comment]
Hi @VDPurohit 

This is a known issue of the PushKit incoming-push delegate method which we are trying to find a workaround. If the `PkPushRegistry` is initialized with the main queue (Apple's Speakerbox sample), there seems to be a threading issue which blocks the UI including sending the `completionHandler` callback and reporting the call to CallKit. For now can you remove
```
func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, 
    for type: PKPushType, completion: @escaping () -> Void) {
        TwilioVoice.handleNotification(payload.dictionaryPayload, delegate: self)
    }
    completion()
}
```

and keep the one without the `completionHandler`?


Let us know if this helps.

Thanks,
-bobie

**Comment by VDPurohit** [comment]
@bchen-twilio 

So if we remove that didReceiveIncomingPushWith delegate method then we are able show UI of incoming call when app is terminated?

Thanks

**Comment by VDPurohit** [comment]
@bchen-twilio 
 
please help us

**Comment by piyushtank** [comment]
@VDPurohit  Bobie is out on vacation and he will be back to work in December. 

Have you tried the workaround Bobie suggested above of removing [this](https://github.com/twilio/voice-quickstart-swift/blob/master/SwiftVoiceCallKitQuickstart/ViewController.swift#L199-L207) callback with completion handler from your app ? You must keep [this](https://github.com/twilio/voice-quickstart-swift/blob/master/SwiftVoiceCallKitQuickstart/ViewController.swift#L199-L207) callback without completion handler.

Let me know if you have any questions.

_Please note that we have ThanksGiving break for the rest of the week, and we will be back to office on Monday. During the ThanksGiving break, our response may be asynchronous._

**Comment by bchen-twilio** [comment]
Hi @VDPurohit 

We have updated the sample apps recently to address the background-suspended issue particularly in iOS 12. Please refer to the pull request for the fixes and apply necessary changes to your application.

I am closing this ticket but please feel free to reopen if you believe the issue still exists.

Thanks
-bobie

**Comment by VDPurohit** [comment]
Thanks for response I need to check updated code.

**Comment by ramohanreddy** [comment]
Hi @VDPurohit 
How did u handled incoming call when app terminate state and background state ?
i created on UI for incoming call when i getting call i need to show custom UI .So how can i do pls help me 
Thanks

**Comment by bchen-twilio** [comment]
Hi @ramohanreddy 

You can follow the quickstart to implement incoming Call alert, either through UI alert or through CallKit, when the app is in different states including backgrounded or terminated.

Thanks
-bobie

**Comment by VDPurohit** [comment]
@ramohanreddy as per suggestion of @bchen-twilio you can find the below function 

// MARK: TVONotificaitonDelegate
    func callInviteReceived(_ callInvite: TVOCallInvite) {
        if (callInvite.state == .pending) {
            handleCallInviteReceived(callInvite)
        } else if (callInvite.state == .canceled) {
            handleCallInviteCanceled(callInvite)
        }
    }

inside "handleCallInviteReceived"  they are implement the alert but you customising UI as per your requirement.

thanks

**Comment by VDPurohit** [comment]
> Hi @VDPurohit
> 
> We have updated the sample apps recently to address the background-suspended issue particularly in iOS 12. Please refer to the pull request for the fixes and apply necessary changes to your application.
> 
> I am closing this ticket but please feel free to reopen if you believe the issue still exists.
> 
> Thanks
> -bobie

ok thanks mine app  requirement change this scenario not include  pick up call feature.
But check this issue as mine earliest.
