### ISSUE TITLE
52134 Invalid APNs device token

### ISSUE THREAD

**Issue by aksthelion** [twilio/voice-quickstart-swift#206]
I'm getting this error when trying to make peer to peer call with app on Test flight. Call works for sandbox mode. 

I've read various posts on generating new CSR etc etc and have created new CSR and VoIP cert two times but still getting this error. 

1) Created a new .certSigningRequest from keychain access
2) Generated new VoIP Services Certificate using above on https://developer.apple.com/account/ios/certificate/distribution/create
3) Downloaded .cer file and added certificate in keychain, Exported .p12 file from keychain
4) Followed instructions on https://github.com/twilio/voice-quickstart-swift to run those three commands to generate key and cert
5) On twilio created a new Push Credential and added Certificate and key by copying and pasting
6) SANDBOX is unticked
7) Change CREDENTIAL SID in my server backend
8) Restarted server

In twilio dashboard I see error: 52134 Invalid APNs device token

Am I missing something here?

**Comment by bchen-twilio** [comment]
@aksthelion I am closing this issue assuming the notification is working fine for the application. Please feel free to re-open if you are still having trouble receiving incoming call notifications.

Thanks,
-bobie
