### ISSUE TITLE
Configure User Notification Settings iOS 10, Swift 3.0

### ISSUE THREAD

**Issue by ahmed-khalil** [twilio/voice-quickstart-swift#21]
I am embedding the call sdk in a project that requires a minimum deployment iOS of 10.0, However the configureUserNotification function is deprecated and this not receiving any phone calls.

Please advise.

Function:

func configureUserNotifications() {
        let rejectAction = UIMutableUserNotificationAction()
        rejectAction.activationMode = .background
        rejectAction.title = "Reject"
        rejectAction.identifier = "reject"
        rejectAction.isDestructive = true
        rejectAction.isAuthenticationRequired = false

        let acceptAction = UIMutableUserNotificationAction()
        acceptAction.activationMode = .background
        acceptAction.title = "Accept"
        acceptAction.identifier = "accept"
        acceptAction.isDestructive = false
        acceptAction.isAuthenticationRequired = false

        let actionCategory = UIMutableUserNotificationCategory()
        actionCategory.identifier = "ACTIONABLE"
        actionCategory.setActions([rejectAction, acceptAction], for: .default)

        let settings = UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: [actionCategory])
        UIApplication.shared.registerUserNotificationSettings(settings)
    }

**Comment by bchen-twilio** [comment]
Hi @ahmed-khalil 

I hope I knew how but this is more like an application specific implementation and unfortunately we are not really familiar with.
