### ISSUE TITLE
How to make conference call ?

### ISSUE THREAD

**Issue by ramohanreddy** [twilio/voice-quickstart-swift#216]
Hi @bchen-twilio ,
how to make conference call in swift 4 .which method i need call .
can any one help me.

Thanks and Regards.

**Comment by bchen-twilio** [comment]
Hi @ramohanreddy 

To join a conference call using the mobile SDK, all you have to do is use an Application SID that uses the [<Conference> TwiML](https://www.twilio.com/docs/voice/twiml/conference) in your Access Token, then make a call using the same `[TwilioVoice call:params:delegate:]` method or `[TwilioVoice connectWithOptions:delegate:]` method in the 3.0 SDK.

-bobie

**Comment by ramohanreddy** [comment]
Hi @bchen-twilio 
I am not able to get this method  "[TwilioVoice connectWithOptions:delegate:]".
I am using bellow pods .
 pod 'TwilioVoice'
 pod 'TwilioClient','1.2'
Can pls give me any document for that.

Thanks&Regards
Ramohan reddy

**Comment by bchen-twilio** [comment]
Hi @ramohanreddy 

The `connect` method is available on the 3.0 SDK and `call` is for the 2.0 Programmable Voice SDK. I am afraid the `1.2` is no longer in active development, in case you are still using it.

-bobie

**Comment by ramohanreddy** [comment]
HI @bchen-twilio 
check this Image.
![Screenshot 2019-03-19 at 11 56 37 AM](https://user-images.githubusercontent.com/18551145/54584726-22930900-4a3e-11e9-9ab6-bc954cf869ef.png)

**Comment by bchen-twilio** [comment]
Hi @ramohanreddy 

Please run `pod repo update` and update your `Podfile` as the version specifier in [this sample](https://github.com/twilio/voice-quickstart-swift/blob/3.x/Podfile) to use the 3.0 SDK.
Thanks.

-bobie

**Comment by ramohanreddy** [comment]
Hi @bchen-twilio 
I am updating pods
but i am getting errors .PFA file

![Screenshot 2019-03-21 at 3 04 05 PM](https://user-images.githubusercontent.com/18551145/54743676-d1744800-4bea-11e9-8b66-daf98841c426.png)

**Comment by bchen-twilio** [comment]
Hi @ramohanreddy 

Please checkout the [migration guide](https://github.com/twilio/voice-quickstart-swift/tree/3.x#migration-guide) which will lead you through the changes you need to apply upgrading from 2.0 to the 3.0 Voice SDK.

Thanks,
-bobie

**Comment by ramohanreddy** [comment]
Hi @bchen-twilio 
i updated new code based on new sdk ,But how i can make conference ,
Is there any delegate method available or else we need to call any API ?.


Thanks &Regards
Ramohan

**Comment by bchen-twilio** [comment]
Hi @ramohanreddy 

Currently the SDK only provides the APIs to connect and disconnect from a call or a conference. You can use the status callback provided in the [Conference TwiML](https://www.twilio.com/docs/voice/twiml/conference) and implement additional communication between your backend service and the mobile app.

-bobie

**Comment by ramohanreddy** [comment]
HI @bchen-twilio 
Here i am facing one issue when i do outgoing call, its asking enter extension number. but when I entered extension number  it says wrong extension number.
In web call  it's  working fine.

Thank&Regards
Ramohan Reddy

**Comment by bchen-twilio** [comment]
Hi @ramohanreddy 

Are you using the `sendDigits:` to send the extension number, and are you sending the digits one by one or all of them at one time in the string parameter of the `sendDigits:` method?

-bobie

**Comment by ramohanreddy** [comment]
Hi @bchen-twilio 
I am directly enter extension using keyboard 
I am not able to get @ sendDigits:  method  and i am not using any method.

Thanks&Regards
Ramohan Reddy

**Comment by bchen-twilio** [comment]
Hi @ramohanreddy 

Can you elaborate how you sent the extension number by "using keyboard?" is it the keyboard of the iOS system Call app?
If your application is integrated with CallKit, you can use `[TVOCall sendDigits:]` method in the `provider:performPlayDTMFCallAction:` delegate method of the `CXProviderDelegate` protocol.

```
- (void)provider:(CXProvider *)provider performPlayDTMFCallAction:(CXPlayDTMFCallAction *)action {
    [self.call sendDigits:action.digits];
    [action fulfill];
}
```

-bobie

**Comment by ramohanreddy** [comment]
Hi @bchen-twilio 
In website  i entered  extension number through  keyboard its taking default.But in mobile i did same  i entered extension through number pad.


Thanks&Regards
Ramohan Reddy

**Comment by bchen-twilio** [comment]
Hi @ramohanreddy 

I just tried calling an ISP service number and was able to send digits successfully to the service by calling `sendDigits:` in the CallKit DTMF callback method.
Perhaps the service number you called is having trouble receiving the digits sent from the SDK. Can you provide us the number you called that was not able to receive the DTMF digits?

-bobie

**Comment by Ruchi0712** [comment]
hello, @ramohanreddy and @bchen-twilio  how can I make a conference call, Is any demo code or tutorials for that?

**Comment by bchen-twilio** [comment]
Closing this issue as answered. 

@ramohanreddy Please feel free to open a new ticket if you still have trouble with the `sendDigits:` API.

@Ruchi0712 We don't have sample code for joining conference call from mobile clients but you should be able to modify your TwiML app to return a response that has a [\<Conference\> verb](https://www.twilio.com/docs/voice/twiml/conference).

Thanks.
-bobie

**Comment by Ruchi0712** [comment]
hello @bchen-twilio 

` func performVoiceCall(uuid: UUID, client: String?, completionHandler: @escaping (Bool) -> Swift.Void) {
        
         let accessToken = accessTokenEndpoint
        
        let connectOptions: TVOConnectOptions = TVOConnectOptions(accessToken: accessToken) { (builder) in
            builder.params = ["to": "", "from" : ""]
            builder.uuid = uuid
        }
        
        call = TwilioVoice.connect(with: connectOptions, delegate: self)
        self.callKitCompletionCallback = completionHandler
    }`
yes I have already changed in TwiML but my question is that In my above method how can I pass multiple numbers in the above method for calling multiple people at a time for the conference.

thanks
-Ruchi

**Comment by bchen-twilio** [comment]
Hi @Ruchi0712 

From the mobile client you can only join the conference as a participant.

-bobie

**Comment by Ruchi0712** [comment]
hi @bchen-twilio 
can you please explain more I didn't catch
thanks
-Ruchi

**Comment by bchen-twilio** [comment]
Hi @Ruchi0712 

Sorry for not responding back to you sooner.
From the mobile client side, you can make a call to a number or a client by connecting to a TwiML app which is demonstrated in the quickstart sample apps. You can also use a `\<Conference\>` verb in the TwiML app and once the call is connected, the mobile client will join the conference as a participant. Currently there is no way for a mobile client to invite multiple mobile clients to join a conference call.

However, in your TwiML response you can make subsequent calls to the clients that you want to invite into a conference and pass the conference room id as custom parameters. The mobile client can use the conference id, which they received inside the notification payload, and dial into the conference like the first inviter participant did.

-bobie

**Comment by Ruchi0712** [comment]
@bchen-twilio Thank you

**Comment by maningyt** [comment]
> Hi @ramohanreddy
> 
> Can you elaborate how you sent the extension number by "using keyboard?" is it the keyboard of the iOS system Call app?
> If your application is integrated with CallKit, you can use `[TVOCall sendDigits:]` method in the `provider:performPlayDTMFCallAction:` delegate method of the `CXProviderDelegate` protocol.
> 
> ```
> - (void)provider:(CXProvider *)provider performPlayDTMFCallAction:(CXPlayDTMFCallAction *)action {
>     [self.call sendDigits:action.digits];
>     [action fulfill];
> }
> ```
> 
> -bobie

But how to get thisfunc provider(_ provider: CXProvider, perform action: CXPlayDTMFCallAction) { ..} delegate method triggered?  I made up a few number button similar to dialPad, don't know how to get system Call's dialpad.

**Comment by bobiechen-twilio** [comment]
Hi @maningyt 

For the case of DTMF from app custom UI, I believe you will need to use the `CXPlayDTMFCallAction` and request via the CallKit controller, like the way to start a new call. Once the action is successfully requested you should receive this callback, and there you can use the `TVOCall.sendDigits()` method.

**Comment by maningyt** [comment]
> Hi @maningyt
> 
> For the case of DTMF from app custom UI, I believe you will need to use the `CXPlayDTMFCallAction` and request via the CallKit controller, like the way to start a new call. Once the action is successfully requested you should receive this callback, and there you can use the `TVOCall.sendDigits()` method.

Thanks for your replay @bobiechen-twilio, I also asked question here: https://github.com/twilio/voice-quickstart-ios/issues/270, I'm using 6.0.0. I tried to make a DTMFCall action as below:
   func performPlayDTMFCallAction(_ digits: String) {
        if let uuid = lastConnectedCall?.uuid {
            let DTMFCallAction = CXPlayDTMFCallAction(call: uuid, digits: digits, type: .singleTone)
            if let provider = callKitProvider {
                provider.setDelegate(self, queue: nil)
                
                let transaction = CXTransaction(action: DTMFCallAction)
                callKitCallController?.request(transaction, completion: {[weak self] error in
                    if let error = error {
                        some_Log.d(msg: " transaction request failed: \(error.localizedDescription)")
                        return
                    }
                    let callUpdate = CXCallUpdate()
                    self?.applySetting(callUpdate: callUpdate)
                    provider.reportCall(with: uuid, updated: callUpdate)
                })
            }
        }
    }
Then sendDigits at provider delegate's method:
func provider(_ provider: CXProvider, perform action: CXPlayDTMFCallAction) {
        if let activeCall = lastConnectedCall, activeCall.callState == .connected {
            let digit = action.digits
            activeCall.sendDigits(digit)
            action.fulfill()
        }
    }

The result is the same as I call  activeCall.sendDigits(digit) directly without creating a CXPlayDTMFCallAction: seems no local dial tone, very minor sound like vocal back from remote. 

https://github.com/twilio/voice-quickstart-ios/issues/270, seems as requested as a feature. Please confirm and let me know if I missed anything. Thanks.

**Comment by bobiechen-twilio** [comment]
Hi @maningyt 

What you observed and described is correct - currently the Voice SDK doesn't add the DTMF tone to the local audio stream. We do have backlog items for tracking the feature request.

Thanks,
-bobie

**Comment by RohitSystematix** [comment]
Hello @bobiechen-twilio, Twilio,
We are working on building an app that makes the client to client call and successfully achieved that.
The problem which we are facing is How we can add a new client in the ongoing client-client using Identity.

We want features like add someone on ongoing call using IOS SDK call.
Please let us know as soon as possible because we need it urgently.

I just want to know what function or delegate, I call when I click on Add Participant on IOS App Side.

**Comment by bobiechen-twilio** [comment]
Hi @RohitSystematix 

To invite another client into an active call you will need to use the <Conference> verb and invite others using the [participant resource API](https://www.twilio.com/docs/voice/api/conference-participant-resource) since the SDK only supports connecting to a TwiML app or accepting an incoming call to the mobile client registered on the device.

**Comment by RohitSystematix** [comment]
![Screenshot 2021-01-05 at 11 10 07 AM](https://user-images.githubusercontent.com/69961167/103610628-9cafbd00-4f46-11eb-9df2-402e156ff488.png)
Thanks @bobiechen-twilio for your reply!
Everything is working fine please check screen shot, I am able to make call successfully  on iOS to Android but I am not able to identify why my device is not successfully register for VOIP Push  notification
I successfully generated for Demo app and also get the notification of incoming call but when I same thing done by different bundle identifier in my actual app then I am not able to register my device for VOIP I we also configured my app VOIP .P12 file on server end but my pushkit delegates not called. And I also give background process like VOIP, Audio Air Play , Push notification. in my plist file I also tried with different network but no luck.

**Comment by bobiechen-twilio** [comment]
Thanks for the update @RohitSystematix and glad to see that the calls are working.
For the PushKit problem, I would suggest that you double check the bundle ID, signing team ID and the entitlement file. Also you might want to make sure the background mode of the app does include `voip` and "Push Notifications" is added to the "Signing & Capabilities" section.

**Comment by RohitSystematix** [comment]
Thanks for the reply @bobiechen-twilio I have successfully make call with one to one and also add third person as a participant but I am not able to find a way how to disconnect or hang up room call like with the use of SID we make a room and add multiple participant (only organizer  have access to add participant ) but how can I terminate all the participant when organizer hang up the call is there any way to when I hang up the call all the participant also disconnected ? Current scenario  is If the the organizer hang up the call remaining participant are still connected.

**Comment by bobiechen-twilio** [comment]
Thanks for the update @RohitSystematix. You can check out the participants resource API for your use case: https://www.twilio.com/docs/voice/api/conference-participant-resource#delete-a-participant-resource
