### ISSUE TITLE
DidReciveRemoteNotification function not calling

### ISSUE THREAD

**Issue by Dhana121205** [twilio/voice-quickstart-swift#219]
After configure my app into twillio as per documentation. binding tested it is working fine. using postman sending nitification tested .post man showing 200 response code but device not called didreciveremotenotification function.

**Comment by Dhana121205** [comment]
<img width="973" alt="Screenshot 2019-03-27 at 1 48 27 PM" src="https://user-images.githubusercontent.com/48981725/55060321-3b7f6800-5097-11e9-89c1-05441d2b0a4b.png">
<img width="977" alt="Screenshot 2019-03-27 at 1 49 20 PM" src="https://user-images.githubusercontent.com/48981725/55060332-3e7a5880-5097-11e9-9c6f-97503cff478d.png">

**Comment by bchen-twilio** [comment]
Hi @Dhana121205 

The Programmable Voice iOS SDK requires the [Apple VoIP Service certificate](https://github.com/twilio/voice-quickstart-swift#bullet7) to deliver incoming call notifications. Once you have created the Push Credential using the VoIP cert, you can use the delegate methods of PushKit to receive the notification and pass it to the SDK.

Thanks,
-bobie

**Comment by Dhana121205** [comment]
@bchen-twilio  certificates created using app push notifications. okay i will try using  Apple VoIP Service certificate and get back to you

**Comment by bchen-twilio** [comment]
Closing issue. Please feel free to open new issue if you run into problem integrating the VoIP service.

Thanks,
-bobie
