### ISSUE TITLE
Application is crashed when call is received.

### ISSUE THREAD

**Issue by chetanPuwar21** [twilio/voice-quickstart-swift#221]
Hi.. guys.. 
     Please help me...

"reason: '-[videoCall2demo.AppDelegate pushRegistry:didReceiveIncomingPushWithPayload:forType:]: unrecognized selector sent to instance 0x1566bc60'"

application is crashed with this type of error.

**Comment by bchen-twilio** [comment]
Hi @chetanPuwar21 

Please check the implementation in your application and ensure the instance of `videoCall2demo.AppDelegate` is correctly assigned to the class that implements the `PkPushRegistryDelegate` protocol.

-bobie
