### ISSUE TITLE
Terminating call invite process

### ISSUE THREAD

**Issue by jbrooksga** [twilio/voice-quickstart-swift#238]
On the Twilio system, in certain situations I need to the call attempt to my iOS client to indicate DialCallStatus = Failed (or canceled).

What element of the ViewController.swift file would be used to purpose cause that condition?

**Comment by bchen-twilio** [comment]
Hi @jbrooksga 

Thanks for choosing the Voice SDK. The sample app we provide simply uses the basic UI element such as the alert to indicate the user that something is going on, for example the alert controller we use for showing the incoming calls. You can definitely choose whatever fits the best for your application's experience.

Cheers,
-bobie

**Comment by jbrooksga** [comment]
Just for future reference I discovered that by using this method:

callInvite.reject()

Twilio sees the DialCallStatus=busy
