### ISSUE TITLE
Mute active call

### ISSUE THREAD

**Issue by reallyseth** [twilio/voice-quickstart-swift#24]
Hi, I'm working on adding a mute call button into my app. I originally thought I could just call VoiceClient.sharedInstance().stopAudioDevice() to mute the call, but that doesn't seem to work. Is there a way using the SDK, or otherwise, to mute an active call?

Thanks so much for the help!

**Comment by bchen-twilio** [comment]
Hi @reallyseth 

Thanks for choosing the Voice iOS SDK and contacting us with the question.
To mute an active call, you will have to use the `muted` property of the `TVOCall` object.
```
  // ObjC
  self.call.muted = YES;
```

-bobie

**Comment by reallyseth** [comment]
Hey, nice and easy! Thanks so much for the quick response!

**Comment by bchen-twilio** [comment]
Happy to help!

Please don't hesitate to contact us in the future if you run into any issue or need any help.

-bobie
Programmable Voice iOS SDK
Twilio SDK Engineering
