### ISSUE TITLE
Unable to get notification of incoming call

### ISSUE THREAD

**Issue by RobSullivan** [twilio/voice-quickstart-swift#243]
### Description
Unable to get notification of incoming call and don't see any errors.

On starting up the app I am expecting to see some confirmation that `pushRegistry` functions have been triggered. 

### Steps to Reproduce

1. Follow QuickStart up to https://github.com/twilio/voice-quickstart-swift#10-receive-an-incoming-call
2. Using `httpie` hit endpoint `http https://anyold.ngrok.io/placeCall ` (`voice-quickstart-server-node`

### Similar issues reported

- [DidReciveRemoteNotification function not calling · Issue #219 · twilio/voice-quickstart-swift · GitHub](https://github.com/twilio/voice-quickstart-swift/issues/219) checked I have created an Apple VoIP Service certificate as detailed in [GitHub - twilio/voice-quickstart-swift: Twilio Voice Quickstart for iOS with Swift](https://github.com/twilio/voice-quickstart-swift#bullet7)

- [I can’t receive an incoming call · Issue #207 · twilio/voice-quickstart-swift · GitHub](https://github.com/twilio/voice-quickstart-swift/issues/207) I don’t see any errors in Debugger.

#### Code

SwiftVoiceQuickstart

#### Expected Behavior

To see some output from `pushRegistry` functions in console log.

#### Actual Behavior

Only get

```
2019-06-30 22:58:16.658689+0100 SwiftVoiceQuickstart[88079:2606538] Twilio Voice Version: 3.0.0
User notificaiton already authorized.
```

#### Reproduces How Often

100% of the time

#### Logs

```
2019-06-30 22:58:16.658689+0100 SwiftVoiceQuickstart[88079:2606538] Twilio Voice Version: 3.0.0
User notificaiton already authorized.
```

#### Voice iOS SDK

3.0.0 via Pods

#### Xcode

10.2

#### iOS Version

12.2

#### iOS Device

iPhone X

**Comment by bchen-twilio** [comment]
Hi @RobSullivan 

Please follow the [setup guide](https://github.com/twilio/voice-quickstart-swift#7-create-voip-service-certificate) and make sure you can initiate the `PkPushRegistry` instance and receive the device token from the `pushRegistry:didUpdatePushCredentials:forType:` callback.

-bobie

**Comment by RobSullivan** [comment]
Thanks @bchen-twilio, I will double check and let you know.

**Comment by RobSullivan** [comment]
Hi @bchen-twilio, forgive my ignorance. Is the `PkPushRegistry`  initiated in on this line?
https://github.com/twilio/voice-quickstart-swift/blob/f0f2f6dc9d94404f8d912f431b13bad78f82f4e6/SwiftVoiceQuickstart/ViewController.swift#L45
I have followed the setup guide referenced and still have the same issue and don't receive the device token from the `pushRegistry:didUpdatePushCredentials:forType:` callback.

Many thanks,

Rob

**Comment by bchen-twilio** [comment]
Hi @RobSullivan 

Please make sure you have configured the application bundle ID and the development team. It should match the bundle ID you used for creating the VoIP Service Certificate. The line (#L45) above will initialize the PushKit, and you will receive the device token used for notification registration in the `pushRegistry:didUpdatePushCredentials:forType:` callback if the project settings is properly configured.

Thanks,
-bobie

**Comment by bchen-twilio** [comment]
Hi @RobSullivan 

Hope things are great. I am curious if your app is still having trouble receiving incoming call push notifications?

Cheers,
-bobie

**Comment by RobSullivan** [comment]
Hey @bchen-twilio, it is but I've put this down for now and will return to it another time.

My issue appears to be in my set up of voip certificates. Even following a generic tutorial for voip certs doesn't function correctly. 👨‍🎓  

Feel free to close this issue and thanks for help with the SDK.
