### ISSUE TITLE
Cannot receive incoming call

### ISSUE THREAD

**Issue by semenag01** [twilio/voice-quickstart-swift#250]
Hello, could you help me please, i have set up the SDK by the tutorial, also i have the server on ROR

The problem is that i cannot receive incoming call, when i have a call from one twilio number  to another.

Both devices have successfully registered voIP device token ```TwilioVoice.register```, it hasn't had any error.

Also i have added push credentials to Twilio Console.

When i try to call to real number i got a call, but when i try to call to Twilio number from Twilio number, the receiver don't call the method ```didReceiveIncomingPushWith```

**Comment by bchen-twilio** [comment]
Hi @semenag01 

Could you provide us a Twilio Call SID which you have trouble receiving the incoming call notification on the callee? Also just curious what is the iOS version your are running on.

Thanks,
bobie

**Comment by semenag01** [comment]
thanks for response. We use IOS 12.3.1. 

What do you mean Twilio Call SID? It is common problem, for example, we faced on these ids

CAcf064775b0a476517a491de4d10f9bba
CAfe4b07a0337b989af5994281833cb071
CAa74eb5f3b14f1478e7ac676c5ff04978
CAd63adf436bc5f97a4d3136305a2e529b
CAc1c0a8d3a1aae44b6863aa8effdd2eae
CAc7b6a9543de793e1056b253204025c7f

As i mentioned push registry delegate method didReceiveIncomingPushWith have never been called, so, i suppose, that we have some trouble, but, unfortunately, i have no ides where.

**Comment by bchen-twilio** [comment]
Hi @semenag01 

Thanks for providing the Call SIDs. They all seemed made for a number, based on the TwiML response of the parent Call SIDs. To make a call to a (mobile) client, please use the [\<Client\> verb](https://www.twilio.com/docs/voice/client/twiml) with the identity of the callee.

Thanks,
-bobie

**Comment by semenag01** [comment]
Thanks, I should manually add this when i create twilio params, like this 
```
 let connectOptions: TVOConnectOptions = TVOConnectOptions(accessToken: token) { (builder) in
                    builder.params = [**"To": "client:\(numberForCall)"**, "From": SMNumberService.shared.currentNumber?.value ?? ""]
                }
```

or it should be added on the server side?

**Comment by bchen-twilio** [comment]
You can pass whatever parameter values from your mobile client when connecting a call, but eventually it is your app server that has to use the <Client> verb to return the response for making a call to another (mobile) client. That way your mobile client should receive the incoming call invite notification.

**Comment by semenag01** [comment]
Thanks a lot, we'll try.

But what about real numbers? 

Server side should detect, something like this, if i have the number in database i'll add word client, otherwise no, am i right?

**Comment by bchen-twilio** [comment]
Yes, your app endpoint can decide wether to make a call to a number or a client or any other supported verbs by Twilo, and Twilio will perform the action based on the TwiML response returned from your app endpoint.

**Comment by semenag01** [comment]
Thanks a lot, give you feedback today.

**Comment by semenag01** [comment]
Thanks a lot, everything works fine.

But we have a strange issue, when we call to a real number from a Twilio number, and the real number rejects the call, after this real number get call again and callback `didDisconncet ` is called only after second rejection.

**Comment by bchen-twilio** [comment]
Hi @semenag01 

Do you have a Call SID of such call?

-bobie

**Comment by semenag01** [comment]
yes, of course, just a moment

**Comment by semenag01** [comment]
Cannot reproduce it right now, if i face with the problem, i will writ here tomorrow, thanks a lot.
