### ISSUE TITLE
What’s the best approach for a current call handling when app is terminated?

### ISSUE THREAD

**Issue by jocelynlih** [twilio/voice-quickstart-swift#252]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Voice SDK Guides](twilio.com/docs/api/voice-sdk)
>  * [GitHub Issues](https://github.com/twilio/voice-quickstart-swift/issues)
>  * [Changelog](https://www.twilio.com/docs/api/voice-sdk/ios/changelog)

We are wondering if there is a better approach for this behavior: when killing the app with a call connected, the current call will leave the other user connected for another minute. 

### Steps to Reproduce

1. On a call, connected status
2. Killing the app
3. The other user stay connected for another minute. 

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

Anything we can do to make the experience better? 
Ideally we want to disconnect the call right away if possible. 

#### Actual Behavior

The call stays connected for 1 minute on the other device. 

#### Reproduces How Often

100%

#### Logs

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

4.0

#### Xcode

10.3

#### iOS Version

All

#### iOS Device

All

**Comment by bchen-twilio** [comment]
Hi @jocelynlih 

One suggestion is to call `.disconnect()` but unfortunately in the case of app being terminated, the app won't get enough time to send out the disconnect message and terminate the call properly using the `[UIApplication beginBackgroundTaskWithExpirationHandler:]` method.

Without doing anything, the Twilio Voice service will terminate the call if it detects silence for longer than 1 minute, which is exactly what you have observed on the other side of the call.

-bobie
