### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by RadagastCH** [twilio/voice-quickstart-swift#253]
### Description

When i tapped on the call button from step 6 I get this error message: 

2019-08-07 17:54:43.940381+0300 SwiftVoiceQuickstart[14819:300177] ERROR:Twilio:[Platform]:Failed to send request, status code: 403
2019-08-07 17:54:44.390360+0300 SwiftVoiceQuickstart[14819:299869] Call failed to connect: Authentication Failed

But I can easily call to my number from TwiMLApps so I guess there's no problem with my node.js server 

Allow arbitrary loads turned to YES 

Any suggestion ?

#### Voice iOS SDK

Twilio Voice Version: 4.1.0  via CocoaPods

#### Xcode

10.3

#### iOS Version

Simulator iPhone Xs iOS 12.4

**Comment by bchen-twilio** [comment]
Hi @RadagastCH 

Can you check if the credentials in your access token are all correct and also can you provide us the error code and error message in the `TVOCallDelegate` callback?

Thanks,
-bobie

**Comment by RadagastCH** [comment]
As I write above, I can call to myself by URL like https://{my ngrok}/makeCall 

this the error message: 

Error Domain=com.twilo.voice.error Code=20151 "Authentication Failed" UserInfo={NSLocalizedDescription=Authentication Failed, NSLocalizedFailureReason=SIP/2.0 403 Forbidden}

from method:
 func call(_ call: TVOCall, didFailToConnectWithError error: Error) {}

this is my token header: 

{
  "alg": "HS256",
  "typ": "JWT",
  "cty": "twilio-fpa;v=1"
}
 also in jwt.io appear message:  Invalid Signature

I use node js server from this https://github.com/twilio/twilio-node

**Comment by RadagastCH** [comment]
I used incorrect Account_SID, now it's work

**Comment by RakeshPatil111** [comment]
> I used incorrect Account_SID, now it's work

Can you tell me ? which fields should be used? I am new and stucked

**Comment by bchen-twilio** [comment]
Hi @RakeshPatil111 

You should be able to find your Twilio account SID in the [developer consoler](https://www.twilio.com/console) (`ACXXXX`). Copy and paste the SID value in the server application where the access token is vended.

-bobie

**Comment by saurav-1998** [comment]
Getting "Call failed to connect: Authentication Failed" error  when click on call button, i have already check Twilio accountsid, api key and api secret key.

**Comment by bobiechen-twilio** [comment]
@saurav-1998 Please contact [Twilio Support](https://support.twilio.com/hc/en-us) with `.all` level of SDK log
