### ISSUE TITLE
Redial from phone app

### ISSUE THREAD

**Issue by reallyseth** [twilio/voice-quickstart-swift#26]
It's really nice to see that missed calls in my app that uses the Twilio SDK show up in the recent calls of the iOS system phone app. When tapping that missed call, it fires `application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void)` in my AppDelegate. 

I found out how to get the contact name from [Apple's Speakerbox CallKit example](https://developer.apple.com/videos/play/wwdc2016/230/). I'm curious, is there a way to get the to and from phone number, or a way to look that up from Twilio to re-call the person in this situation?

**Comment by reallyseth** [comment]
Okay, I'm on the right track. I need to pass in the incoming phone number to the CXHandle that I'm registering with callkit. So to get the incoming phone number, I'm checking the TVOCallInvite that comes in from the `callInviteReceived` method. But the from value is the Twilio number that the call is being dialed into, not the actual from number. Is there another way to get the from number from the TVOCallInvite object?

**Comment by bchen-twilio** [comment]
Hi @reallyseth 

Thanks for the great question.
To help you get the "from" value for your app usage, first I need to know how the incoming call is generated - is it from a PSTN number to your Twilio number and then routed to a mobile client's identity? or is it from another Twilio (mobile) client?

For the first case (from PSTN), in your TwiML response you can put the number in the `callerId` of the **Dial** verb. The number will eventually show in the `from` property of the `TVOCallInvite`/`TVOCall` object. 
Please note that this number has to be a valid phone number. Non-numerical characters in the `callerId` will be dialpad-translated into numbers, for example if you put `bobie` in the `callerId`, the receiver will see `26243` as `from`.

For the second case (client to client), please make sure you have the correct identity in the caller's access token and leave the TwiML's Dial `callerId` with you Twilio number. This way the Twilio Voice service will use the caller's identity as the "from" value in the incoming call push notification.

Please let me know if this helps.

-bobie
