### ISSUE TITLE
Problem accept call ios 13 build, tested on ios 12.4.1

### ISSUE THREAD

**Issue by klimentLambevski** [twilio/voice-quickstart-swift#264]
After the update to 5.0.0, accept call invite is not working and the  following error is thrown 

```
   let acceptOptions: TVOAcceptOptions = TVOAcceptOptions(callInvite: self.callInvite!) { (builder) in
            builder.uuid = callInvite.uuid
        }
        let res = callInvite.accept(with: acceptOptions, delegate: self)
        
        print("TVOCall [\(res.state.rawValue)]  [\(res.uuid)]")
        
``` 

ERROR:Twilio:[Platform]:AVAudioSession setActive Error Domain=NSOSStatusErrorDomain Code=561017449

xcode 11, iOS 13, tested on iOS 12.4.1

**Comment by klimentLambevski** [comment]
I managed to resolve the error but `callInvite.accept` does not connect to the call. The status of the call stays `ringing` until it becomes `no-answer`

**Comment by bchen-twilio** [comment]
Hi @klimentLambevski 

Do you have Call SIDs of the problematic calls and SDK log? It seems the SDK was not able to finish establishing the call connection.

I have tried and found that there is a place in the quickstart that needs to be updated: the application needs to keep the ownership of the accepted call object, otherwise the call object will be deallocated when it goes outside of the method scope and the call connection is never completed.

The call object destroyed before it goes out of the method scope:
```
func performAnswerVoiceCall(uuid: UUID, completionHandler: @escaping (Bool) -> Swift.Void) {
    // ...
    let acceptOptions: TVOAcceptOptions = TVOAcceptOptions(callInvite: self.callInvite!) { (builder) in
        builder.uuid = self.callInvite?.uuid
    }
    let call = self.callInvite?.accept(with: acceptOptions, delegate: self)
    // ...
}
```

The call connects after accepted and kept as a property instance:
```
var call: TVOCall?

func performAnswerVoiceCall(uuid: UUID, completionHandler: @escaping (Bool) -> Swift.Void) {
    // ...
    let acceptOptions: TVOAcceptOptions = TVOAcceptOptions(callInvite: self.callInvite!) { (builder) in
        builder.uuid = self.callInvite?.uuid
    }
    self.call = self.callInvite?.accept(with: acceptOptions, delegate: self)
    // ...
}
```

With the small fix I am able to accept and connect the call between the caller and callee.
Let me know if this helps.

Thanks,
-bobie

**Comment by bchen-twilio** [comment]
Hi @klimentLambevski 

FYI, I've posted a quick PR to address this issue: https://github.com/twilio/voice-quickstart-swift/pull/265

-bobie

**Comment by klimentLambevski** [comment]
@bchen-twilio Thanks for the reply, this small fix did the job. Kudos to you 🥇

**Comment by markathomas** [comment]
Hi, I have this fix in my app but I still experience the same issue with XCode 11 and iOS 13.3

**Comment by markathomas** [comment]
Here's my answer function:
```
    func performAnswerVoiceCall(uuid: UUID, completionHandler: @escaping (Bool) -> Swift.Void) {
            if let ci = self.callInvite {
                let acceptOptions: TVOAcceptOptions = TVOAcceptOptions(callInvite: ci) { (builder) in
                    builder.uuid = ci.uuid
                }
                NSLog("performAnswerVoiceCall: answering call")
                let theCall = ci.accept(with: acceptOptions, delegate: self)
                self.call = theCall
                self.callKitCompletionCallback = completionHandler

                guard #available(iOS 13, *) else {
                    self.incomingPushHandled()
                    return
                }
            } else {
                NSLog("No CallInvite matches the UUID")
            }
        }
```
