### ISSUE TITLE
How to make sendDigits play DTMF locally?

### ISSUE THREAD

**Issue by paxtonhare** [twilio/voice-quickstart-swift#270]
### Description

I added a button to call `call.sendDigits()` to a gather verb on the backend. The DTMF tones are not audible on my client. Is there a way to play the DTMF tones locally? I was able to verify this issue in ios 12 and ios 13.

Thanks in advance.

### Steps to Reproduce

1. Press the call button
2. Wait for a connection then press a custom button to call sendDigits (seen below)
When pressed, the DTMF tones are not audible locally.

#### Code

```swift
@IBAction func sendDigits(_ sender: Any) {
        if let call = self.call {
            call.sendDigits("12345#")
        }
    }
```

#### Expected Behavior

I'd like to be able to hear DTMF tones locally.

#### Actual Behavior

I'm unable to hear DTMF tones locally.

#### Reproduces How Often

100%

#### Voice iOS SDK

Twilio SDK 5.0 via cocoapods

#### Xcode

Xcode 11

#### iOS Version

12.4 and 13.1.2

#### iOS Device

iPhone 6 Plus (12.4)
iPhone 7 Plus (13.1.2)

**Comment by paxtonhare** [comment]
The only somewhat relevant thing I could find was this:
`[CLIENT-3611] Added DTMF tone local playback when TVOCall.sendDigits is called.`

located here: https://www.twilio.com/docs/voice/voip-sdk/ios/2x-changelog#200-beta9-may-11-2017

**Comment by bchen-twilio** [comment]
Hi @paxtonhare 

Thanks for reaching out. The 5.0 SDK currently does not support tone on the local client when calling the `.sendDigits()` method. We will investigate with the current codebase and evaluate.

Cheers,
-bobie

**Comment by maningyt** [comment]
Same question, just tried on 6.0 iOS SDK to iPhone with iOS14, there's no tone on local client on  .sendDigits("1"). However the callee can hear the tone. Please take a look. Thanks.
