### ISSUE TITLE
[Feature request] Ability to create TVOCallInvite without pushkit

### ISSUE THREAD

**Issue by ryango** [twilio/voice-quickstart-swift#271]
My app only wants to be able to receive calls while in the foreground. I don't care about voIP pushes and I don't want to integrate CallKit as it breaks my desired UX. I'd much rather poll my service for a call sid and generate the call invite from that instead of the push dictionary, but it looks like there are a few other dictionary elements that aren't generated by my twiML app and handleNotification fails without them. How can I handle incoming calls without pushkit?

**Comment by ryango** [comment]
going to close this as I found a solution using queues in my twiml app

**Comment by idelgado** [comment]
For others that may be interested in this alternative, Twilio supports putting calls in a [queue](https://www.twilio.com/docs/voice/twiml/queue). Once an incoming call is in a queue, you can connect an outbound call via TwiML to the named queue.
