### ISSUE TITLE
Code conflict in example and migration guide "4 -> 5"

### ISSUE THREAD

**Issue by gerchicov-bp** [twilio/voice-quickstart-swift#277]
### Description

https://github.com/twilio/twilio-voice-ios/blob/Releases/iOS-13-Migration-Guide.md#migrating-from-twilio-voice-3x4x-to-5x
readme contains section:
```
Please note that if the app is updated but never launched to perform the registration, the mobile client will still receive "cancel" notifications, which could cause the app terminated by iOS if the VoIP push notification is not reported to CallKit as a new incoming call. To workaround and avoid app being terminated on iOS 13, upon receiving a "cancel" notification you can report a dummy incoming call to CallKit and then end it on the next tick:
```
In the same time this example doesn't contains another code (which seems to be older).

The main problem for me is after twilio updating the app doesn't receive incoming calls without of additional relaunching.

### Steps to Reproduce

None

#### Code

https://github.com/twilio/twilio-voice-ios/blob/Releases/iOS-13-Migration-Guide.md#migrating-from-twilio-voice-3x4x-to-5x
https://github.com/twilio/voice-quickstart-swift/blob/963170d9aafc0c37c9a83b10a9f6cf8b9ee45f34/SwiftVoiceQuickstart/ViewController.swift
Code inside `func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void)`.

#### Expected Behavior

One common code chunk in both places

#### Actual Behavior

Different chunks of code and it is not clear how to mix them

#### Reproduces How Often

Always

#### Logs

No logs are required - the issue exists without of running code.

### Versions

4.x
5.x

#### Voice iOS SDK

Migration from 4.x to 5.x

#### Xcode

11.2

#### iOS Version

12.x
13.x

#### iOS Device

independent from device

**Comment by bchen-twilio** [comment]
Hi @gerchicov-bp 

If I am understanding this correctly, you mean that the quickstart itself doesn't have the workaround by "this example doesn't contains another code"?

One of the necessary steps of the migration guide is to perform a registration by calling the `TwilioVoice.register()` method (apps might have different implementations but it usually requires a re-launch) to subscribe for only the "call" notification, while the previous versions of SDK subscribe to both "call" and "cancel" notifications. The latter will cause the apps being terminated by the system on iOS 13 since the "cancel" notification normally won't be reported to CallKit.

Thanks,
-bobie

**Comment by gerchicov-bp** [comment]
Hello @bchen-twilio
I already have the code similar to this one:
https://github.com/twilio/voice-quickstart-swift/blob/963170d9aafc0c37c9a83b10a9f6cf8b9ee45f34/SwiftVoiceQuickstart/ViewController.swift

The question is should I add to my code `if (payload.dictionaryPayload["twi_message_type"] as! String == "twilio.voice.cancel") {` from your migration guide and everything inside it? If yes then how to combine it with the existing code?

**Comment by bchen-twilio** [comment]
Hi @gerchicov-bp 

In case you think your application can still receive "cancel" notifications (you should not if the application performs registration with the new SDK), you can add the workaround before calling `TwilioVoice.handleNotification()`: https://github.com/twilio/voice-quickstart-swift/blob/963170d9aafc0c37c9a83b10a9f6cf8b9ee45f34/SwiftVoiceQuickstart/ViewController.swift#L271

-bobie
