### ISSUE TITLE
Error - 52143 The push notification was rejected by APNs

### ISSUE THREAD

**Issue by Sadmansamee** [twilio/voice-quickstart-swift#282]
### Description

In Twilio dashboard I see **Error - 52143 The push notification was rejected by APNs** and my call never reach out partner.

### Steps to Reproduce

1. Steps to Reproduce
2. Created a new .certSigningRequest from keychain access.
3. Generated new VoIP Services Certificate.
4. Downloaded .cer file and an added certificate in keychain, Exported .p12 file from keychain
5. Followed instructions on https://github.com/twilio/voice-quickstart-swift to run those three commands to generate key and cert.
6. On Twilio created a new Push Credential and added Certificate and key by copying and pasting.
7. SANDBOX is **ticked**.
8. Change CREDENTIAL SID in my server backend.
9. Restarted server.
10. Changed Client name
11. Call Client to Client Call or https://github.com/twilio/voice-quickstart-php Place Call API

Expected Behavior
Make a voice call.

Actual Behavior
Call start but never reach out to my partner.

#### Logs

```
bindingType | "apn"
-- | --
primaryCorrelationId | "CA9e65853e0cd6f5c80468d7451d30af40"
bindingSid | "BSf5f2ee9a43533c9e20ba8f0c805a470b"
providerMessageId | "f4f49d39-8270-cfdf-d7f1-71730a32864c"
requestId | "RQd3b915f0b2a0d31d6eb22afa07a88f56"
notificationSid | "NT6c19515056ff902ab7265f31c2450fe9"
module | "APNSBA"
description | "The device token does not match the specified topic."
isPassthrough | "true"
deliverySid | "DA088816ef814bbafa627fa116db6bba4f"
fromReference | "CR7927172c2f1546e39b91e57f2e0f6dc7"
```

### Versions

All relevant version information for the issue.

#### Voice iOS SDK
5.1.0

#### Xcode
11.2.1

#### iOS Version
13.1.3 - 13.2.1

#### iOS Device
iPhone XR, iPhone 7

**Comment by bchen-twilio** [comment]
Hi @Sadmansamee 

I checked the Push Credential SID and found that the credentials are actually derived from a regular APN service certificate, instead of a VoIP Service certificate.

-bobie

**Comment by Sadmansamee** [comment]
How do I fix it?

**Comment by Sadmansamee** [comment]
I selected this
![](https://user-images.githubusercontent.com/16326574/43967764-065d3ed0-9c7a-11e8-9d4d-a45e81e4d2d8.png)

**Comment by Sadmansamee** [comment]
Do I need to export without passwords ?

**Comment by bchen-twilio** [comment]
Hi @Sadmansamee 

The "VoIP Services Certificate" is the correct option and exporting with password should be necessary. Is there any chance that the certificate & key were exported from a .p12 of an APNS certificate?

-bobie

**Comment by Sadmansamee** [comment]
Thank you for your coordination, I have created push and voip cred with same CSR now it's working fine, but one problem I'm currently facing is when I get a call, It starts ringing successfully but just after 2-3 seconds it stops after printing **callInviteReceived** on **reportIncomingCall**

**Comment by bchen-twilio** [comment]
Hi @Sadmansamee 

Thanks for trying updating the certificate and glad to see the issue fixed.

What is the app state (active/backgrounded/terminated/device locked) when the call invite was received but stopped after 3 seconds? Is it possible for you to provide SDK logs and Twilio Call SIDs when this happens?

-bobie

**Comment by Sadmansamee** [comment]
@bchen-twilio it is working all the time. but one issue that I'm facing, I show a timer whenever I get **connected** state. but whenever ringing starts I get **connected** state, and **ringing** state stays only for 1-2 secs. and getting **connected** state when actually it rings.

**Comment by bchen-twilio** [comment]
Hi @Sadmansamee 

This is the default behavior of the Programmable Voice - the caller client will receive the "connected" callback once the signaling and the media connections are established between the caller and Twilio. To only receive the "connected" callback when the call has been answered by the callee, please use [the answerOnBridge flag](https://www.twilio.com/docs/voice/twiml/dial#answeronbridge) in your <Dial> verb.

I am closing this ticket since the original issue seemed to have been resolved. Please feel free to reach out to us if you run into any issue.

Cheers,
-bobie
