### ISSUE TITLE
Crashed: IncomingVideoStream EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by aksthelion** [twilio/voice-quickstart-swift#289]
Twilio video 2.6
Random crash, can't reproduce, don't have any more log

Crashed: IncomingVideoStream EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000094981dbe1ea0

Crashed: IncomingVideoStream
0  TwilioVideo                    0x101178414 _hidden#23214_ + 944896
1  TwilioVideo                    0x10117839c _hidden#23214_ + 944776
2  TwilioVideo                    0x1011b9744 _hidden#25871_ + 1211952
3  TwilioVideo                    0x100edf5ac _hidden#5835_ + 308084
4  TwilioVideo                    0x100ec873c _hidden#4694_ + 214276
5  TwilioVideo                    0x100ec88d0 _hidden#4702_ + 214680
6  TwilioVideo                    0x100ef0230 _hidden#6621_ + 376824
7  libdispatch.dylib              0x1a01cb184 _dispatch_client_callout + 16
8  libdispatch.dylib              0x1a01a8710 _dispatch_lane_serial_drain$VARIANT$armv81 + 564
9  libdispatch.dylib              0x1a01a9128 _dispatch_lane_invoke$VARIANT$armv81 + 400
10 libdispatch.dylib              0x1a01b243c _dispatch_workloop_worker_thread + 576
11 libsystem_pthread.dylib        0x1a021af88 _pthread_wqthread + 276
12 libsystem_pthread.dylib        0x1a021dad4 start_wqthread + 8

**Comment by bchen-twilio** [comment]
Hi @aksthelion 

Please file an issue in the [twilio-video-ios](https://github.com/twilio/twilio-video-ios) repository.
