### ISSUE TITLE
Failed to verify bitcode

### ISSUE THREAD

**Issue by rajapandian-dev** [twilio/voice-quickstart-swift#32]
I'm getting the below error when i export with enterprise certificate. I have bitcode enabled for my project.
Failed to verify bitcode in TwilioVoice.framework/TwilioVoice:
error: Cannot extract bundle from /var/folders/ss/vf5vy9d56bj2dkpxrxtw501r0000gq/T/XcodeDistPipeline.uKB/Root/Payload/AppName.app/Framework

I'm using latest beta version.

**Comment by bchen-twilio** [comment]
Hi @rajapandian-dev 

Sorry that you are having trouble exporting the app. 
Could you share a bit more about how the SDK is integrated into you application project? did you install it via the Cocoapods lib or by manual drag-n-drop into app's Embedded Binaries?

We've actually been running the App Store submission as one of our release validation steps and beta9 also works great with bitcode enabled.

I've done some research on the internet and I hate to suggest this but could you try clean the build folder and restart Xcode, and then give it another try?

Thanks
-bobie

**Comment by rajapandian-dev** [comment]
Hi @bchen-twilio 

Thanks for the response. I did by drag and drop and added the script in Build phase as described in twilio document. Now i moved to pod, able to export an IPA. For twilio pod, i had reinstall the pod repo. All good now. I'm not sure why it wasn't working by drag and drop method.

Thanks.

**Comment by bchen-twilio** [comment]
That's great! @rajapandian-dev
Just in case, what version of Xcode are you currently using?

**Comment by rajapandian-dev** [comment]
@bchen-twilio hi, Using Xcode 8.2.1. Thanks.
