### ISSUE TITLE
Unable to install SDK

### ISSUE THREAD

**Issue by ojhakapil** [twilio/voice-quickstart-swift#33]
I need VOIP capability in my iOS app. For that purpose I'm trying to install the Programmable Voice SDK via cocoapods but getting the below error:

[!] Unable to find a specification for `TwilioVoice (= 2.0.0-beta9)`

I'm using cocoapod version 1.2.0

**Comment by bchen-twilio** [comment]
Hi @ojhakapil 

Thank you for choosing the Programmable Voice iOS SDK.
Could help me with two thing?
- make sure that you have `source 'https://github.com/twilio/cocoapod-specs'` in your `Podfile` like [this example](https://github.com/twilio/voice-quickstart-swift/blob/master/Podfile).
- run `pod repo update` to allow the Cocoapods library to update all the pods references.

Let me know if this helps.
Thanks.

-bobie

**Comment by ojhakapil** [comment]
Hi @bchen-twilio 

running pod repo update did the trick for me.

Thank you for your quick reply.

**Comment by bchen-twilio** [comment]
👍
