### ISSUE TITLE
Not getting notification for an incoming call

### ISSUE THREAD

**Issue by ojhakapil** [twilio/voice-quickstart-swift#34]
I'm using SwiftVoiceQuickstart.xcodeproj to make and receive VoIP calls via Programmable Voice SDK for iOS. I'm able to make an outgoing call. But, when I'm trying to test incoming calls using /placeCall after my ngrok server url, I'm not getting any notification for incoming call on my iPhone, but I'm getting a 200 OK message on server.

- I have created VoIP certificate from my Apple developer account, exported it as .p12, and then extracted the corresponding certificate and private keys as .pem.
- I have successfully created the Push Credentials on Twilio.
- On my Apple Developer account, Push notification for development is "Configurable" while it's "Enabled" for distribution.

Please let me know if I'm missing anything.

Thanks in advance

**Comment by bchen-twilio** [comment]
Hi @ojhakapil 

Before asking you to provide us your account credentials, could you go to the [Programmable Voice dashboard](https://www.twilio.com/console/voice/dashboard) and check the upper-right corner and see if you can find any errors/warnings related to the possible notification delivery failure being logged?

On the SDK/app side, are you seeing successful result of the registration in the callback block? verbose SDK log would definitely help us diagnose - we need to see whether it's the registration failure or the notification delivery.

We've also have a compiled [FAQ](https://www.twilio.com/docs/api/voice-sdk/ios/faq) and hopefully you might find something useful.

You should be able to find my email in the profile. Please provide us the Account SID, Push Credential SID and SDK verbose log.

**Comment by ojhakapil** [comment]
Hi @bchen-twilio 

Thanks for your quick reply.

I went to the dashboard and found that there was multiple error logs saying:

> **52134-RTD Notification : Invalid APNs device token**

On the app side, I'm able to register successfully for notifications since I'm getting the message 

**> Successfully registered for VoIP push notifications**

**Comment by bchen-twilio** [comment]
Hmm... a few possible causes I can think of:
- The CSR file for generating the VoIP Service cert was used for creating APNS certificate.
- Your testing the app in development environment, but the sandbox option was not checked when creating the Push Credential. Twilio will then send the notification to Apple's production endpoint, with your device token requested with a development entitlement.

Sorry about the successful registration confusion, but we definitely missed something here. Unfortunately on the Twilio Notify side, we really can't do much to validation the device token or credentials embedded in the certificate, but surface the error when failed to delivery the notifications.
 
I can check the account SID and push credential SID combination and see if I can find any immediate errors.

-bobie

**Comment by ojhakapil** [comment]
I'm pretty sure that the CSR I used for creating VoIP Service certificate was earlier used for creating an iOS Development/Distribution certificate but not APNS certificate. I also checked the the Sandbox option when I created Push credentials.

I will create a fresh CSR and try with that.

I also sent you my Account SID and Push Credentials on bchen@twilio.com.

**Comment by ojhakapil** [comment]
Used a fresh CSR and it worked.

Thank you bobie for your support.

**Comment by bchen-twilio** [comment]
Nice!
Yeah I tried the account SID and push credential but didn't see anything wrong. Sorry it's so nontrivial to just get incoming call notification work. I've also checked the errors logged under your account and was about to ask you if the device token from the PushKit.

Anyway, glad that it's working for you now.
Looking forward to seeing your awesome Voice app!

cheers
-bobie

**Comment by gaoguangli** [comment]
@ojhakapil What do you mean the fresh CSR?

**Comment by bchen-twilio** [comment]
Hi @gaoguangli 

In order to make sure the VoIP Service certificate does not mess with existing APNS certificate or other certificates, we would suggest SDK users to use a new CSR (certificate signing request) file using Keychain Access when creating the VoIP cert in the Apple developer portal.

Thanks.

**Comment by Mehul18292** [comment]
Hi @bchen-twilio 

As you suggested, I have created new CSR file and created new VOIP certificates using this and added to my account. But I am still unable to receive calls. FYI, my outgoing call working perfectly fine.

Possible issue: the push credentials are added in master account. And for getting access token, I am using sub account. Is that the issue? Do I need to add push credentials to each of my sub accounts.

**Comment by bchen-twilio** [comment]
Hi @Mehul18292 

Thanks for getting back.
For security reasons, credentials are not shareable between accounts, event master and subaccounts.

-bobie

**Comment by rochapablo** [comment]
https://stackoverflow.com/questions/53888958/twilio-incoming-calls-not-working-for-ios

**Comment by ayesharahman494** [comment]
Hi, i am also not receiving a notification on my iphone , the error says : "Credential SID is not specified" , could someone guide me through this??

**Comment by bchen-twilio** [comment]
Hi @ayesharahman494 

Can you share more details about the problem you are seeing? Based on the error message you got I am assuming that you were able to register with the access token although it does not have a Push Credential SID and later when you called the client, Twilio was not able to send the notification. Can you help us check if the access token you are using has a valid `push_credential_sid` value?

Thanks,
-bobie

**Comment by ayesharahman494** [comment]
Solved it, thank you
