### ISSUE TITLE
Multi user management

### ISSUE THREAD

**Issue by ahbou** [twilio/voice-quickstart-swift#40]
Hi
Our app supports multi-users and I'm having a bit of trouble unregistering the previous user.
For example if I'm logged in as User A, when I logout and login as User B, I still get the calls that should go to A.
On logout I do call unregister(withAccessToken accessToken: String, deviceToken: String ...)
Is that the right process to follow?

I was using beta-9 and upgraded to beta-10. 

Thank you

**Comment by bchen-twilio** [comment]
Hi @ahbou 

I've just tried the unregister and register with new identity steps and it worked okay for me - not able to call the previously registered user but able to call the new one.

Is this happening all the time? could you also provide us the verbose SDK log? just to make sure all the callbacks are called correctly and (un)registrations are good.

Also could it be possible that the device experiencing the identity confusion was used with different VoIP Service certificate or mixing sandbox and production Push Credential SIDs?

-bobie

**Comment by ahbou** [comment]
Hi Bobie
It was indeed a certificate issue. I was running both from Xcode but the server was using the production credentials.
Thanks for the prompt response 👍

**Comment by bchen-twilio** [comment]
Awesome @ahbou!
Let us know any time if you run into any issue in the future.
