### ISSUE TITLE
Unable to receive VoIP notification for incoming call

### ISSUE THREAD

**Issue by zubairuddin** [twilio/voice-quickstart-swift#45]
Hey there,

I've set up Twilio Programmable Voice SDK for iOS in my app. I'm able to successfully make outgoing calls, but I'm not getting any notification for incoming call. The method didReceiveIncomingPush is not getting called.

I'm getting the below error on Twilio dashboard:

> 52162 - RtdNotification : Credentials do not belong to used account.

Please let me know what could be the issue.

Thanks.

**Comment by bchen-twilio** [comment]
Hi @zubairuddin 

Thanks for choosing the Twilio Voice SDK. Glad that you've managed to make outgoing calls.
Without the credentials unfortunately I won't be able to tell you what exactly is wrong, but by the description you are probably mixing the Push Credential SID between the main and sub-accounts. For security reason, things are basically not shared between accounts, even main and sub-accounts.

I am happy to take a quick look at your Twilio Account SID and the Push Credential SID and check if there is anything other than the accounts. You should be able to find my email. Please don't post any of your Twilio (or non-Twilio) credentials here :p

cheers
-bobie

**Comment by zubairuddin** [comment]
Thanks for your reply. I will provide you the credentials for twilio account which I am using.

**Comment by zubairuddin** [comment]
Here are the twilio credentials I'm using:

Email: prateek.jain1@ideavate.com <Prateek.jain1@ideavate.com>
Password: ideavate@12345

Let me know if you need anything else from me.

Thanks,
Zubair

**Comment by bchen-twilio** [comment]
Hi @zubairuddin 

I've deleted your previous comment.
Please change your Twilio account password immediately.
Thanks.

I'll follow up with you in the email.

-bobie

**Comment by bchen-twilio** [comment]
Hi @zubairuddin 

I ran the Account SID and Push Credential SID you provided but they seem to be good.
I did see a couple of failures under this account matching the original issue, but the Push Credential SID is different from the one you gave me.

Could you please check if the Push Credential SID ending with `2586` is working for you?
Thanks.
-bobie

**Comment by zubairuddin** [comment]
Yes, the same push credentials SID ending with `2585` is working now without changing anything. But same was not working earlier. Can you tell me what could have been the issue? 

I really appreciate your support.

**Comment by bchen-twilio** [comment]
Hi @zubairuddin 

Actually the one ending with `2586` never appeared in the error log under your account. The database showed quite a few of failures about "push credential sid does not belong to account" but they are all the same push credential sid that ends with `1d04`. The application, mobile or server, must have been vending the the wrong push credential sid for the access token.

If the one ending with `1d04` is not valid or not used anymore, please make sure:
- you have unregistered all the identities registered with this credential sid
- you are not vending tokens with this credential sid
- you have deleted this credential sid from the Twilio account console

Thanks
-bobie

**Comment by zubairuddin** [comment]
Hi @bchen-twilio ,

The Push Credentials SID ending with `1d04` is associated to a different demo account I used earlier, which has expired now.

I will remove that SID from Twilio account and will make sure it is not used anywhere.

Thanks for your support.

**Comment by bchen-twilio** [comment]
👍

**Comment by ramohanreddy** [comment]
Hi @bchen-twilio 
Is there any code for receive VOIP notification in swift.
