### ISSUE TITLE
CallKit: when to use it?

### ISSUE THREAD

**Issue by julien-c** [twilio/voice-quickstart-swift#52]
Hello,

I am slightly confused by the fact that there are two different Xcode projects here, with/without Callkit.
Haven't seen a documentation item about this. Any reason? Are both implems mostly identical except for CallKit, or are there other divergence planes?

**Comment by bchen-twilio** [comment]
Hi @julien-c 

The reason we have a separate project for CallKit quickstart is to keep the code simple without a lot of condition blocks to decide whether to integrate CallKit system functionality or not. This way we can make sure the best practice of using the Twilio Voice iOS with the CallKit framework is surfaced to our SDK users and developers have no hard time understanding.

Feel free to just follow whichever project that suits your use case and design the best.

Thanks
-bobie
