### ISSUE TITLE
Not receiving .voIP push notifications

### ISSUE THREAD

**Issue by andresag** [twilio/voice-quickstart-swift#534]
### Description

I have followed the steps as shown in the "Voice iOS SDK Getting started" guide.
* I've set up my own python Twilio backend (version 6.10.0)
* Created an Apple's VoIP Certificate and use the cert and key to generate the push credential.
* Uploaded said credential to Twilio
* Request an access token from the client and check that everything is correct (voice grant, push credential and identity)
* Implemented PushKit in the client and got the device token of type .voIP

I am able to trigger `didReceiveIncomingPushWith`  when sending a test push notification from the CLI (using curl). But, when trying to trigger an incoming call push notification using `/place-call` endpoint on my backend, nothing arrives.

#### Expected Behavior

A .voIP push notification arrives at `didReceiveIncomingPushWith`.

#### Actual Behavior

`didReceiveIncomingPushWith` is not triggered.

#### Reproduces How Often

Every time.

#### Twilio Call SID(s)

CAde1b0174a21f5bbce336333ec13ed47a

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

6.5.0

#### Xcode

14.3 (beta)

#### iOS Version

16.4.1

#### iOS Device

iPhone SE (3rd gen)

**Comment by bobiechen-twilio** [comment]
Hi @andresag thanks for reaching out.

From the Call SID I did see that there was no push notification delivery record in the system, although the record does show that there is one push notification binding associated with the callee's client identity. Did you run into any issue when calling the `register()` method with the token?

-bobie

**Comment by andresag** [comment]
Hi @bobiechen-twilio, thanks for getting back to me.

Not running into any issues. The register seems to end without errors.
I can see in the Console calls log that the call is terminated with a `480 Temporarily Unavailable`. Besides that, I am not sure how can I further debug this problem.

**Comment by bobiechen-twilio** [comment]
Thanks @andresag.
Please provide SDK debug log or error information you are seeing specifically about the registration.

**Comment by andresag** [comment]
It was a problem with the certificate and the push credential assigning in my local backend. It is solved.
Issue can be closed. Thank you for your help @bobiechen-twilio.
