### ISSUE TITLE
Call logs in native Phone app are always "Canceled Call" , even I successfully make the call.

### ISSUE THREAD

**Issue by jessicawang143143** [twilio/voice-quickstart-swift#56]
I have this problem in my app, and I tried in the sample code "SwiftVoiceCallKitQuickstart" , get the same result.
### Steps to Reproduce

1. Make a call and the other side answer the call.
2. Hang up the call.
3. Check the native phone calllog.

#### Expected Behavior

The call log should say "Outgoing Call"

#### Actual Behavior
The call log now say "Canceled Call"

#### Reproduces How Often
100%

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

2.0.0-beta14 (August 15, 2017)

#### Xcode

Version 8.3.3 (8E3004b)

#### iOS Version

10.3.3(14G60)

#### iOS Device

 iPhone SE

![img_3831](https://user-images.githubusercontent.com/23222136/29547304-5d9918e2-874d-11e7-8dfe-7b6571f6a9a1.PNG)

**Comment by bchen-twilio** [comment]
Hi @jessicawang143143 

Thanks for reporting this. I tried and did see "Canceled Call" in the call app history.
I've created [this PR](https://github.com/twilio/voice-quickstart-swift/pull/59) to address this bug in the sample app.

cheers
-bobie

**Comment by jessicawang143143** [comment]
Hi @bchen-twilio

Thanks for replying. I have another problem when I get an incoming call and try to answer a call, get a failed message like this:
call:didFailWithError: Generic error
Error Domain=com.twilio.voice.error Code=31000 "Generic error" UserInfo={NSLocalizedDescription=Generic error, NSLocalizedFailureReason=Inside makeCall, failed to connect the call. Error: 120049}
Thanks for your help

**Comment by bchen-twilio** [comment]
Hi @jessicawang143143 

Could you enable .verbose log level and send it to my email? you know where to find it :)
Thanks.

**Comment by jessicawang143143** [comment]
@bchen-twilio 

Get this error on a production app, no more logs for it. I have my dev version logs on, if I get this prob again, will send you the log .
Thanks

**Comment by bchen-twilio** [comment]
Hi @jessicawang143143 

We've just merged the PR which fixes the original "canceled call" issue. Could you take a look at [the changes of the PR](https://github.com/twilio/voice-quickstart-swift/pull/59) or pull the latest to your app?

I'll go ahead a close this ticket for now. Please feel free to open a new issue once you reproduce the call failure and of course, the SDK log :)

-bobie

**Comment by jessicawang143143** [comment]
Hi @bchen-twilio 

Thank you so much for the help of this issue. 

Best regards,
Jessica
