### ISSUE TITLE
Add Carthage support for building the Twilio Framework

### ISSUE THREAD

**Issue by rickyproy** [twilio/voice-quickstart-swift#58]
Our application uses carthage, and we would love to see support for carthage for adding the sdk to our codebase.

Thanks!

**Comment by ceaglest** [comment]
Hi @rickyproy,

Thanks for the feature request! 

We are currently working on automating our release pipeline to support Carthage for [Twilio Video](https://github.com/twilio/video-quickstart-swift/issues/103). Once this is done we will apply the same learnings to the Voice SDK.

Best,
Chris Eagleston

**Comment by Iraniya** [comment]
Hello Chris,
I like to know if you now support Carthage.
Thanks.

**Comment by ceaglest** [comment]
Hi @Iraniya,

Unfortunately we do not support Carthage for the Voice or Video SDKs yet. However, our Chat and Sync teams have recently added Carthage support and we hope to incorporate the same process improvements for Voice. I will keep this ticket up to date as we get closer on this feature.

https://www.twilio.com/docs/api/chat/sdks#carthage-integration

Best,
Chris

**Comment by Iraniya** [comment]
HI Chris,
thanks for your feedback, I'm stuck at integrating twilio video SDK can you help me out. 
thank you very much, I'm attaching stackover flow link rahther than creating mess here. :-p 
https://stackoverflow.com/questions/47407659/twillio-framework-compression-issue-while-pushing-the-code-to-github

**Comment by ceaglest** [comment]
Hi Iraniya,

For Video you should take a look at this issue.

https://github.com/twilio/video-quickstart-swift/issues/110

Best,
Chris

**Comment by bchen-twilio** [comment]
Hi everyone,

We are super excited to tell you that the Voice iOS SDK v2.0.1 is also available on https://github.com/twilio/twilio-voice-ios for Carthage integration. Please follow the instructions in the repo README.
