### ISSUE TITLE
Unable to find a specification for `TwilioVoice (= 2.0.0-beta15)`

### ISSUE THREAD

**Issue by ppierson** [twilio/voice-quickstart-swift#65]
### Description

I downloaded the quickstart sample and am receiving the following error when performing `pod install`
```
[!] Unable to find a specification for `TwilioVoice (= 2.0.0-beta15)`
```
I have not altered the quick start project in any way.

### Steps to Reproduce

1. Download the `voice-quickstart-swift` project from github.
2. In terminal,  type `pod install` under the project path. (Must have cocoapods gem)

#### Expected Behavior

The TwilioVoice pod should download and integrate into the project.

#### Actual Behavior

Error output in terminal:
```
[!] Unable to find a specification for `TwilioVoice (= 2.0.0-beta15)`
```

#### Reproduces How Often

100%

**Comment by bchen-twilio** [comment]
Hi @ppierson 

Could you try `pod repo update` and let the `pod` library update the repository DB then try again `pod install`?
Thanks.

-bobie

**Comment by ppierson** [comment]
That worked, thank you for the quick reply!
