### ISSUE TITLE
Question : Preventing an incoming phone call to come over a running Twilio call

### ISSUE THREAD

**Issue by zubairuddin** [twilio/voice-quickstart-swift#69]
Hi Twilio Support,

I'm using TwilioVoice SDK 2.0.0-beta14, things are working great. However, our client has raised a question and we have to reply to the client.

The question is : When we are on a Twilio call and at the same time there is an incoming phone call, the incoming phone call rings over the running Twilio call. Is there a way to prevent this?

Thanks

**Comment by bchen-twilio** [comment]
Hi @zubairuddin 

Unfortunately there is nothing we can do to prevent interruption by the PSTN incoming call.
With CallKit, you can at least configure the `CXCallUpdate` to enable "hold" (`.supportsHolding = YES`) and then tap "hold and accept".

Please note that there is currently a known issue in the Voice iOS SDK that audio might be lost after resuming the call from the interruption. We are actively working on fixing the issue.

Thanks,
bobie

**Comment by zubairuddin** [comment]
Hi @bchen-twilio 

Thanks for your reply.

So is using CallKit the only option I have?
Is holding supported without CallKit? If not, what is the other approach I can follow? It's really awkward for the clients when they are on a Twilio call and suddenly there phone starts ringing.

Thanks
Zubair

**Comment by bchen-twilio** [comment]
Hi @zubairuddin 

That's a good question - technically CallKit isn't the only option. The SDK or the iOS application can subscribe to the `AVAudioSessionInterruptionNotification` and do necessary sound device operations respectively when the interruption begins and ends. Both the CallKit and interruption-handler approaches need the "hold" function from the Voice SDK, which we are still working on the implementation.

As for the PSTN incoming call interruption itself, I don't think there is a way to prevent it ringing in the middle of another active. This is the same even in other applications. The SDK needs to provide APIs for the application to make sure the call and audio can resume properly after the interruption ends.

Hope this answers your question.

bobie

**Comment by zubairuddin** [comment]
Thanks @bchen-twilio 

Will try and communicate this to our client.

-Zubair
