### ISSUE TITLE
Upload to iTunes connect fails for apps compiled with 2.0.0-beta17 via CocoaPods

### ISSUE THREAD

**Issue by elyalvarado** [twilio/voice-quickstart-swift#72]
### Description

Uploading to iTunes connect an app compiled using the cocoapod version 2.0.0-beta17 gets rejected with the following message:

> ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [Happy.app/Frameworks/TwilioVoice.framework/inject_credentials.sh] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"

Note: I'm using fastlane, but everything works if I use TwilioVoice version 2.0.0-beta16

### Steps to Reproduce

1. Compile, sign the app with production certificates and Upload to iTunes connect using fastlane

#### Expected Behavior

The app should not be rejected

#### Actual Behavior

The app is rejected

#### Reproduces How Often

It happens always

#### Logs

```
ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [Happy.app/Frameworks/TwilioVoice.framework/inject_credentials.sh] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"
```

### Versions

Fastlane 2.6.1

#### Voice iOS SDK

2.0.0-beta17 via CocoaPods

#### Xcode

9.0

#### Workaround

Deleting the file Pods/TwilioVoice/TwilioVoice.framework/inject_credentials.sh causes the app not to be rejected, however I don't know if its going to cause problems

**Comment by bchen-twilio** [comment]
Hi @elyalvarado 

Thanks for reporting the issue. Yes, the temporary solution would be manually deleting the `inject_credentials.sh` inside the framework and upload the app to the store again.
Sorry for the inconvenience and we will release a fix ASAP.

-bobie

**Comment by bchen-twilio** [comment]
Hi @elyalvarado 

We've just released beta18 and removed the script file.
Please update the podspec reference and upgrade the framework.

Thanks again for reporting the issue.
bobie

**Comment by bchen-twilio** [comment]
Hi @elyalvarado 

I hope you are doing well and ready to enjoy the weekend.
I am assuming this issue is already fixed with the release of beta18 and I am going to close this issue.
Please feel free to reopen or open a new issue if you run into any problem or have any feedback in the future.

Thanks!
-bobie
