### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by sarankumar291** [twilio/voice-quickstart-swift#76]
If I end the call and then try to call back, then I do not hear any audio while inside the call. I am able to connect on both ends just as I would expect, but I just hear no audio.

Please help me. Thanks in advice.

**Comment by bchen-twilio** [comment]
Hi @sarankumar291 

Could you please share some more details with us?
- SDK version
- the steps to reproduce the problem
- does this happen every time?
- are the caller and callee both on iOS devices?
- is this happening on a specific device model? we've also found a no-audio issue but only on iPhone8/8+ (iOS 11.0.x)
- last but not least, verbose level SDK log will definitely help us debug the issue
```
    [[TwilioVoice sharedInstance] setLogLevel:TVOLogLevelVerbose];
    [[TwilioVoice sharedInstance] setModule:TVOLogModulePJSIP logLevel:TVOLogLevelVerbose];
```

Thanks
-bobie

**Comment by bchen-twilio** [comment]
Hi @sarankumar291 

How are things? Have you heard of the Programmable Voice SDK 2.0 GA release? We've fixed couple of audio-related issues and updated the API. The latest quickstart should have enough information how to use the latest API.
I am assuming the issue has been resolved and closing this issue. Please feel free to open a new issue if you run into any in the future.

Thanks
-bobie
