### ISSUE TITLE
TVOCall attributes nullability

### ISSUE THREAD

**Issue by siberianisaev** [twilio/voice-quickstart-swift#79]
### Description

_uuid_ attribute of TVOCall marked as **nonnull**, but it can be nil.

### Steps to Reproduce

1. calls from one iOS simulator to another one

#### Code

```objc-c
@interface TVOCall (CallKitIntegration)

/**
 * @brief UUID of the call.
 *
 * @discussion Use this UUID for CallKit methods.
 */
@property (nonatomic, strong, nonnull) NSUUID *uuid;
```

#### Expected Behavior

_uuid_ must be marked as **nullable**

#### Actual Behavior

 Swift app crashes when it's nil
```
<TVOCall: 0x600000110e90>
  uuid: (null)
```

**Comment by siberianisaev** [comment]
```
@property(readonly, strong, nonatomic, nonnull) NSString *from;
--
`From` value of the call.This may be `nil` if the call object was created by calling the `<[TwilioVoice call:params:delegate:]>`

```

Same thing for other attributes all marked as **nonnull**

**Comment by bchen-twilio** [comment]
Thanks for reporting the issue @siberianisaev.
We've created a bug ticket and will be working on it in the following week.

In the meantime could you also share some more info with us about
- what steps did you do to result in the problem
- does this happen every time? (it seems so)
- SDK log will also help

Thanks
-bobie

**Comment by bchen-twilio** [comment]
Hi @siberianisaev,

We've released the Programmable Voice iOS SDK beta20 and updated the nullability notations. Now `to`, `from` and `uuid` of `TVOCall` are marked as `nullable`.

Thanks,
-bobie

**Comment by siberianisaev** [comment]
thanks
