### ISSUE TITLE
Unable to register for VOIP push.

### ISSUE THREAD

**Issue by warisappify** [twilio/voice-quickstart-swift#81]
### Description

I need help in following scenario.
I am facing issue while using TwilioVoice-Swift on * TwilioVoice.register(withAccessToken
 deviceToken:) * .
It says *Error Domain=com.twilio.voice.error Code=20101 "Invalid access token" *. 

Can you guide me how to solve this issue as i am earlier using same url for getting token to use it with TwilioClient and its works perfect now i need to implement CallKit with PushKit to receive call while app is not active but its saying Invalid token.

### Steps to Reproduce

1. [Step one]
Trying to register on twilio with access token and device token. In method *pushRegistry(_ registry: PKPushRegistry, didUpdate credentials: PKPushCredentials, forType type: PKPushType) *

#### Code

```swift
public func pushRegistry(_ registry: PKPushRegistry, didUpdate credentials: PKPushCredentials, forType type: PKPushType) {
        if (type != .voIP) {
            return
        }
        self.deviceTokenString = credentials.token.reduce("", {$0 + String(format: "%02x", $1)})
        print("voip token: ", self.deviceTokenString!)
 guard let deviceToken = self.deviceTokenString else {
                return
            }
            TwilioVoice.register(withAccessToken: self.token, deviceToken: deviceToken) { (error) in
                if (error != nil) {
                    NSLog("An error occurred while unregistering: \(error?.localizedDescription ?? "")")
                }
                else {
                    NSLog("Successfully unregistered from VoIP push notifications.")
                }
            }
}
```

#### Expected Behavior

Successfully register for device and access token.

#### Actual Behavior

Came error with description

Error Domain=com.twilio.voice.error Code=20101 "Invalid access token"

#### Reproduces How Often

[What percentage of the time does it reproduce?]
100%
#### Logs

```
2017-11-24 12:58:05.560693+0500 CareCinch[1662:697656] [VERBOSE TwilioVoice] Application did become active
2017-11-24 12:58:05.560919+0500 CareCinch[1662:697656] [DEBUG TVOReachability] Reachability Flag Status: -R ------- networkStatusForFlags
2017-11-24 12:58:10.565308+0500 CareCinch[1662:697656] [VERBOSE TwilioVoice] Registering for Twilio push notifications
[DEBUG TVONotificationClient] Register for push notifications.
2017-11-24 12:58:12.151782+0500 CareCinch[1662:697925] [DEBUG TVONotificationClient] Completed registration request.
2017-11-24 12:58:12.152435+0500 CareCinch[1662:697656] [ERROR TwilioVoice] Inside register:deviceToken:completion:, failed to register for Twilio push notifications. Error:Invalid access token
2017-11-24 12:58:12.156081+0500 App[1662:697656] An error occurred while unregistering: Invalid access token
```

### Versions

2.0.0-beta20

#### Voice iOS SDK
2.0.0-beta20  via CocoaPods

#### Xcode
Xcode 9.1

#### iOS Version
iOS 11.1

#### iOS Device
iPhone 6 Plus

**Comment by bchen-twilio** [comment]
Hi @warisappify 

Could you check if the access token has valid expiry and account credentials?

Thanks
-bobie

**Comment by warisappify** [comment]
Thanks for quick reply.

Can you guide me how to check the expiry and account credentials of a token?

**Comment by warisappify** [comment]
@bchen-twilio i just put my token on [https://jwt.io](url) and it give me the following response.

Can you explain me why its invalid signature.

<img width="602" alt="screen shot 2017-11-24 at 3 59 23 pm" src="https://user-images.githubusercontent.com/24873180/33207722-999b4e82-d130-11e7-93cf-eeba741b61a8.png">

**Comment by bchen-twilio** [comment]
Hi @warisappify 

Thanks for providing the screenshot. Actually you are just one step away: please change the `programmable_voice` under the `grants` to just `voice`.

By the way, is this token generated using one of the Twilio help library? if yes please also let us know which language you are using.

Thanks!

**Comment by warisappify** [comment]
Hi @bchen-twilio 

We are using Twilio helper library of PHP and generating the token using following code example.
[https://www.twilio.com/docs/api/rest/access-tokens?code-sample=code-creating-an-access-token-voice&code-language=php&code-sdk-version=5.x](url)

**Comment by warisappify** [comment]
I change the `programmable_voice` to `voice` but its still giving following error.

Error Domain=com.twilio.voice.error Code=20107 "Invalid access token signature"

**Comment by warisappify** [comment]
@bchen-twilio 
Here is the logs after changing the settings and upgrading the library to 5.16 for PHP on server end.

[VERBOSE TwilioVoice] Application did become active
[DEBUG TVOReachability] Reachability Flag Status: -R ------- networkStatusForFlags
[VERBOSE TwilioVoice] Registering for Twilio push notifications
[DEBUG TVONotificationClient] Register for push notifications.
[DEBUG TVONotificationClient] Completed registration request.
[ERROR TwilioVoice] Inside register:deviceToken:completion:, failed to register for Twilio push notifications. Error:Invalid access token signature
An error occurred while unregistering: Invalid access token signature

Error Domain=com.twilio.voice.error Code=20107 "Invalid access token signature"

**Comment by bchen-twilio** [comment]
Hi @warisappify 

The error code indicates that the `secret` (came with API Signing Key when it was generated) does not match the API Signing Key. Please make sure you are using a valid API Signing Key and secret pair when generating the Access Token.

In case the `secret` is missing, you will need to generate a new Signing Key and keep both the key and the secret in a safe place.

-bobie

**Comment by warisappify** [comment]
@bchen-twilio 

Issue solved, Thanks.
