### ISSUE TITLE
Conflicting TVOCallDelegate method signatures in Swift 4

### ISSUE THREAD

**Issue by BayPhillips** [twilio/voice-quickstart-swift#82]
### Description

Just updated to the beta20 on Cocoapods and it looks like two of the call delegate methods signatures are the same when attempting to be used in Swift 4:

`- (void)call:(nonnull TVOCall *)call didFailToConnectWithError:(nonnull NSError *)error;`
and
`- (void)call:(nonnull TVOCall *)call didDisconnectWithError:(nullable NSError *)error;`

These methods are named the same, take the same types of parameters in the same order, and have the same return type and that's not allowed!

### Steps to Reproduce

1. Install the beta20 from cocoapods
2. Implement the `TVOCallDelegate` stubs in Swift 4
3. Attempt to compile

![image](https://user-images.githubusercontent.com/537211/33249372-1ded2a52-d2f8-11e7-913c-e72061878eed.png)

#### Code

```swift
    func call(_ call: TVOCall, didDisconnectWithError error: Error?) {
        
    }
    
    func call(_ call: TVOCall, didFailToConnectWithError error: Error?) {

    }
```

#### Voice iOS SDK

2.0.0-beta20 via CocoaPods

#### Xcode

9.1

#### iOS Version

iOS 11.1

#### iOS Device

Any

**Comment by bchen-twilio** [comment]
Hi @BayPhillips 

Thanks for reporting the issue with detailed descriptions 👍 
We'll investigate and see how we can improve the API signature for better Swift compatibility.
Thanks.

-bobie

**Comment by bchen-twilio** [comment]
Hi @BayPhillips 

I've just tried using the quickstart with Swift4 compiler (by changing `Swift Language Version` in the project settings). I did have to update some of the methods of the `PkPushRegistryDelegate` protocol but I didn't see the conflict with the `TVOCallDelegate` methods.

One difference is that the `error` of `call:didFailToConnectWithError:` is mandatory.
Quickstart sample by the team:
```swift
    func call(_ call: TVOCall, didFailToConnectWithError error: Error) {

    }
```

While in your snippet the `error` is optional:
```swift
    func call(_ call: TVOCall, didFailToConnectWithError error: Error?) {

    }
```

Can you try and see if the compiler still complains?
Thanks.

-bobie

**Comment by bchen-twilio** [comment]
Hi @BayPhillips 

How are things going?
Are you able to get the same compiler error using the Swift quickstart? I am trying to compare and see if there is anything we missed in the project settings so that we know how to reproduce the same error and fix it.

Thanks
-bobie

**Comment by bchen-twilio** [comment]
Hi @BayPhillips 

I am finally able to get the same compiler errors and it has nothing to do with my previous theory about the optional unwrapping. I was able to reproduce the error messages by commenting out one of the following protocol methods
```swift
  func call(_ call: TVOCall, didFailToConnectWithError error: Error) {
  }

  func call(_ call: TVOCall, didDisconnectWithError error: Error?) {
  }
```

Though the error message doesn't quite make sense but after uncommenting and making sure all the `TVOCallDelegate` methods are implemented then the app builds.

Hope this helps.
-bobie

**Comment by BayPhillips** [comment]
Hey @bchen-twilio you're right, looks like it'll actually compile now. I also updated onto XCode 9.2 so maybe that helped too?

**Comment by bchen-twilio** [comment]
Hi @BayPhillips 

That's great 👍  It actually builds fine on my machine with Xcode9.1.
I am going to close this issue for now, but please feel free to contact us in the future if you run into any issue.

Cheers,
-bobie
