### ISSUE TITLE
Thread registration returned error code 120022

### ISSUE THREAD

**Issue by hasgar** [twilio/voice-quickstart-swift#83]
**Thread registration returned error code 120022. Twilio Client APIs will be executed in the main thread. Please file an error report with this description.**

Getting this error and crashing when disconnecting the call

Swift 3.1
iOS 10.0
Twilio Voice 2.0.0-beta20

**Comment by bchen-twilio** [comment]
Hi @hasgar 

Thanks for reporting the issue. We are actively working on improving the threading model and safety of the SDK and will soon release a new version with the improvement.

Just curious, is this bug happening every time when you try to disconnect the call or does it require some specific steps?

Thanks
-bobie

**Comment by bchen-twilio** [comment]
Hi @hasgar 

We've just released 2.0.0-beta21 which includes an internal threading model & safety improvement. It should also address the issue you are experiencing.

Thanks
-bobie

**Comment by bchen-twilio** [comment]
Hi @hasgar 

I am assuming the 2.0.0 Voice SDK is working well with you application and I'll go ahead and close this ticket. Please feel free to reopen if you are still experiencing this particular error or create a new one if you run into any in the future.

Thanks.
-bobie
