### ISSUE TITLE
Time lag between addRenderer and actual video is shown on TVIVideoView.

### ISSUE THREAD

**Issue by mitolog** [twilio/voice-quickstart-swift#87]
### Description
There is a time lag after `videoTrack.addRenderer(self.remoteView!)` until participant's video 
 is actually shown on the remoteView, say 3~7 sec on VideoCallKitQuickStart project. On my own project, it last about 30 sec maximum. It's depends on network bandwidth. But, I don't want to expose a blank view, which shows only remoteView background color, to the user.

How can I detect actual timing that the remote participant's video is shown on remoteView?
Or, Is there any ideas to prevent showing blank view until actual video is shown, or remove time lag?

room type: group
video codec: VP8
recording: disabled
maximum participants: 50

I tried with 2 device, and 2 situations:
wifi - wifi
wifi - 3G

In both situation, time lags are exist though durations are differed.

### Code
I assume time lag will start from this code:

ViewController.swift:323 on VideoCallKitQuickStart

```
    func participant(_ participant: TVIParticipant, addedVideoTrack videoTrack: TVIVideoTrack) {
        logMessage(messageText: "Participant \(participant.identity) added video track")

        if (self.participant == participant) {
            setupRemoteVideoView()
            videoTrack.addRenderer(self.remoteView!)
        }
    }
```

### Versions
TwilioVideo 1.3.8

#### Xcode
9.0

#### iOS Versions / iOS Devices
10.2: iPhone6 plus
10.0.1: iPhone5

**Comment by bchen-twilio** [comment]
Hi @mitolog 

Thanks for choosing Twilio Programmable Video SDK. Can you create a ticket in the [Swift Video Quickstart repo](https://github.com/twilio/video-quickstart-swift)?

**Comment by mitolog** [comment]
@bchen-twilio 
sorry I just posted support ticket.

**Comment by bchen-twilio** [comment]
@mitolog no worries.
By the way, have you heard about the Programmable Voice SDK? You can create your awesome VoIP app using the Voice SDK with less than hundred lines of codes ;)

-bobie

**Comment by mitolog** [comment]
@bchen-twilio 
Thanks for the info. Does Voice SDK supports also Video? I took a glance of Voice SDK but I need Video functions, so I chosen Video SDK.

**Comment by mitolog** [comment]
sorry, I mistaken. it's voice-quickstart-swift repository :(

**Comment by bchen-twilio** [comment]
Unfortunately the Voice SDK doesn't support video and the various media capabilities like the Video SDK does. The Voice mainly provides mobile applications the ability to integrate with the [TwiML](https://www.twilio.com/docs/api/twiml) functions of Twilio, and VoIP is one of the great features.

**Comment by mitolog** [comment]
@bchen-twilio Thanks for the info again. Let me try if needed in the future! Can you remove this issue? or Should I?

**Comment by bchen-twilio** [comment]
You are welcome!
Happy to close the issue for you and please feel free to reach out to us in you run into any problem using the SDKs.

Cheers.
