### ISSUE TITLE
Error when I try to register VOIP Pushes

### ISSUE THREAD

**Issue by warisappify** [twilio/voice-quickstart-swift#89]
### Description

Hi,

Getting this error when trying to register for push notifications:

`Error Domain=com.twilio.voice.error Code=31301 "Http status: 400. Unexpected registration response." UserInfo={NSLocalizedDescription=Http status: 400. Unexpected registration response.}`

I've created credentials as per your guide and everything seems to be fine.

But get this error. Any ideas?

**Comment by bchen-twilio** [comment]
Hi @warisappify 

Are you getting this specific error code consistently every time when you call `TwilioVoice.register()`?
It would be great if you can send me the Access Token and the Push Device Token so we can have a closer look at what's causing the issue. You know where to find my email address.

Thanks.
-bobie

**Comment by warisappify** [comment]
Hi @bchen-twilio 

Yes i am facing this issue after every `TwilioVoice.register()`. But

I solved this last night as my token is not generating correct due to missing SID of push credentials on server side. As we move build to live from staging and constants are missed at live server.
After adding that its works fine.
Thanks for the help.

**Comment by bchen-twilio** [comment]
Hi @warisappify 

Cool!
Glad that things are working 👍 

-bobie
