### ISSUE TITLE
Unable to receive the Call on iOS. Error-52134 Invalid APNs device token

### ISSUE THREAD

**Issue by Harshjain2094** [twilio/voice-quickstart-swift#93]
Me and my team have been working on past 3 days to get Incoming call working on the iOS and Android app to app calling. My Android developer have successfully created the App to App calling in there app.

But I only get the error that **Error-52134 Invalid APNs device token**

VoIP push notifications is not being received by the app and I have tried with both Production CSR and Sandbox CSR

### Steps to Reproduce

1. My Python developer got the code from repo [https://github.com/twilio/voice-quickstart-server-python](url) and started it.
2. I got the got the code from this repository and built the app in iPhone 6+
3. I tried to make a call from the python quickstart server.

#### Expected Behavior

A call to be received on the app.

#### Actual Behavior

I got nothing but an error in Twilio Debugger. **Error-52134 Invalid APNs device token**

#### Reproduces How Often

Every single time.

Please help me solve this.

Thank You!

**Comment by Harshjain2094** [comment]
@bchen-twilio I am emailing you the Account SID, Push Credentials SID, one Notification SID of the failed attempt and Call SID for which this notification was made.

**Comment by Harshjain2094** [comment]
@bchen-twilio The problem is resolved by one of your mentioned answers in some other issue. There was a problem on my end while parsing the accessToken.

**Comment by bchen-twilio** [comment]
Hi @Harshjain2094,

Glad that the issue was resolved. I will close this one and please feel free to open a new ticket if you run into any issue in the future.

Thanks.
-bobie
