### ISSUE TITLE
Make a call to Android Device

### ISSUE THREAD

**Issue by kalyanpkumar** [twilio/voice-quickstart-swift#99]
I have my app working on both iOS and Android devices..

So how to place call from iOS device to Android device. As i can configure only one type of push credentials in Twilio voice console. 

Can you please provide me some insights on this?

**Comment by bchen-twilio** [comment]
Hi @kalyanpkumar 

In the Twilio account dev console you should be able to create multiple Push Credentials with different service types (FCM/GCM/APN). You can then determine which Push Credential SID to return in your `/accessToken` endpoint based on the HTTP request parameter:
```
// two Push Credential SIDs were created
CRdeadbeeFORiOSApplications
CRdeadbeeFORAndroidApplications
```

```
// token request from your iOS app
token = stringFromURL("https://myserver.io/accessToken?platform=ios")
// token request from your Android app
token = stringFromURL("https://myserver.io/accessToken?platform=android")
```

```
// /accessToken endpoint
push_platform = request.form.get('platform')
if push_platform == "ios":
  push_credential = CRdeadbeeFORiOSApplications
elif push_platform == "android":
  push_credential = CRdeadbeeFORAndroidApplications

// generate access token using the chosen push_credential
```

Hope this helps.
Please let us know if you have any trouble creating multiple Push Credentials in the Twilio console.
Thanks.

-bobie
